### ISSUE TITLE
Gson parser able to parse illegal json

### ISSUE THREAD

**Issue by celeritas9** [google/gson#1021]
I am using the gson in my code and it's able to parse an invalid json.

Json simply is:
{ dummy : "abc"}

Whereas, I think the valid json should be:
{ "dummy" : "abc"}

Is it really an issue?

Also, why JsonParser sets the leniency of JsonReader to true every time? Shouldn't it read the leniency value from the JsonReader supplied?

**Comment by JakeWharton** [comment]
It's legacy, broken behavior we can't change unfortunately.

To work around it you can use the `getAdapter` method to look up a `TypeAdapter` for the type you want to serialize/deserialize. Then use its `fromJson` / `toJson` methods instead of those on the `Gson` object which will provide strict behavior.
