### ISSUE TITLE
fromJson() hangs and silently crashes with graphics Path

### ISSUE THREAD

**Issue by djdance** [google/gson#1140]
I need to serialize Path object and faced with weird impossibility. App just stops.

Let's place a simple test right in onCreate()

```
    import com.google.gson.Gson;
    import android.graphics.Path;

    ...

    Gson g=new Gson();
    Path p=new Path();
    p.addRect(0,0,100,100, Path.Direction.CCW);
    String s=g.toJson(p).toString(); 
    p = g.fromJson(s, Path.class); //(1)

```
run the app and wait ~5-15 sec. First it hangs, then will silently crash. If you comment the string (1), it will work. If you change (1)'s Path.class to p.getClass() or new TypeToken&lt;Path>(){}.getType() - it will not help. So the reason is in fromJson.

I tried 4 devices with SDK from 17 to 25, and behavior is the same. What's wrong, how to store Path to JSON? my assumption is infinite Path's loop, which is confusing GSON.

**Comment by JakeWharton** [comment]
You should never serialize an object that is outside of your control and which weren't explicitly designed for serialization. In this example, the internals of Path are an implementation detail. The correct way to serialize this would be to register a TypeAdapter for the type and use its public API to decide what representation you want in JSON.

In Moshi, the spiritual successor to Gson, we actually forbid serializing anything in the android.* package by default unless you register a manual adapter to define the JSON format. Unfortunately it's too late to change Gson to do the same.

As to the actual cause here, your guess of a reference cycle in the implementation details of Path is the cause.

**Comment by djdance** [comment]
thank you for the detailed answer.
I've spent >2 hours trying to store Path, thus let this issue helps another men.

The simple solution of such a task is some workaround with creating parallel ArrayList to store changes in path, i.e. you leave path for fast drawing, but use array for serializing.
