### ISSUE TITLE
java.lang.securityException

### ISSUE THREAD

**Issue by kailandrewhamili** [google/gson#1152]
Caused by: java.lang.SecurityException: Can not make a java.lang.reflect.Field constructor accessible

I am experiencing this runtime error when deserializing JSON to Java object.

That error does not show up on Android API 17 up to API 21 (API 22 not tested). It show on API 23 and up.

**Comment by JakeWharton** [comment]
You should not have a Field in your model. Either move it outside or mark it transient.

**Comment by kailandrewhamili** [comment]
What do you mean?

This is my Model:

`public class ProductList extends Model {

    @Column(name="productId")
    public Integer productId;

    @Column(name="productName")
    public String productName;

    @Column(name="productTypeId")
    public Integer productTypeId;

    @Column(name="amount")
    public double amount;`

**Comment by JakeWharton** [comment]
Then it's in Model or the subclass that whatever library you are using is
generating.

**Comment by kailandrewhamili** [comment]
Can you please check my repository 'SmarAirportApp' i have an assumption that Gson does not work on Nougat and up.

**Comment by JakeWharton** [comment]
Gson is used by tens or maybe hundreds of thousands of apps which run on
Nougat and above. Something is putting a java.lang.reflect.Field into an
object that you are passing to Gson. It's probably another library or tool
which is rewriting your classes. Based on your @Column annotation I'll take
a wild guess that it's either Realm or ObjectBox, and you should consult
the authors of that library as to the best way to deal with what they're
doing in order to use Gson.

**Comment by kailandrewhamili** [comment]
Okay. I'll try to remove those annotations and I'll see if it works.

**Comment by kailandrewhamili** [comment]
I use Gson together with ActiveAndroid.
