### ISSUE TITLE
Documention lacks clear ways to do unserialize from ArrayList<YourType>

### ISSUE THREAD

**Issue by dataf3l** [google/gson#1201]
Given this use case is probably common, why not make an example?

**Comment by inder123** [comment]
Feel free to send a PR

**Comment by Marcono1234** [comment]
I think the Usage Guide [shows that quite well](https://github.com/google/gson/blob/master/UserGuide.md#TOC-Collections-Examples); though that is for `Collection`, but you can easily adjust it for work for `ArrayList`.

**Comment by dataf3l** [comment]
Wow, 4.5 years... this brings memories.

Also, the issue being closed without being resolved (in my opinion) to my satisfaction, which is less than awesome. 

As I grep for ArrayList on the README there isn't still a clear way to do it and my guess is people like me, mere mortals, who don't know that an ArrayList IS a Collection, will perhaps still have trouble doing it, as we may lack encyclopedic knowledge of the java class hierarchy.

I did learn something today though, but spending 5 years to close the issue, and not even solving the issue, feels a bit, I don't know, well, less than awesome, why even have issues.

Honestly, I don't even work for the company that had me working on this issue any more, so the issue is stale at this point.

Also "feel free to send a PR" doesn't feel like the best contribution in my mind either.

We did eventually move on to Serde and rust (I think, memory is a bit fuzzy) so we are not even using this product to my knowledge.

To satisfy my curiosity, I asked Github Copilot to just do the example, it wrote this:

```
/*
this program unserializes JSON into an array list
*/
import java.util.ArrayList;
import java.util.List;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
package main;
public class jsonparser {
    public static void main(String[] args) {
        String example = "[{\"name\":\"John\",\"age\":30},{\"name\":\"Jane\",\"age\":25},{\"name\":\"Jack\",\"age\":20}]";
        JsonParser parser = new JsonParser();
        JsonElement element = parser.parse(example);
        JsonArray array = element.getAsJsonArray();
        List<Person> people = new ArrayList<Person>();
        for (JsonElement jsonElement : array) {
            JsonObject jsonObject = jsonElement.getAsJsonObject();
            String name = jsonObject.get("name").getAsString();
            int age = jsonObject.get("age").getAsInt();
            Person person = new Person(name, age);
            people.add(person);
        }
        for (Person person : people) {
            System.out.println(person.toString());
        }
        
    }
}
```

It looks to me like it will take over our job guys...

I hope it is useful, but be forewarned, *this code is untested*.
I hope if people need to unserialize into an array list, this works, honestly, I sincerely do.

**Comment by Marcono1234** [comment]
> Wow, 4.5 years... this brings memories.
> 
> Also, the issue being closed without being resolved (in my opinion) to my satisfaction, which is less than awesome.

Sorry for the inconvenience. We are currently in the process of cleaning up some old issues, and I assumed due to the age of this issue it is no longer relevant.

> As I grep for ArrayList on the README there isn't still a clear way to do it and my guess is people like me, mere mortals, who don't know that an ArrayList IS a Collection, will perhaps still have trouble doing it, as we may lack encyclopedic knowledge of the java class hierarchy.

I think the main point of these user guide sections is to show how Gson can be used for generic types (which applies to `ArrayList<E>` as well). Including examples for every commonly used generic type (`HashSet`, `HashMap`, `LinkedList`, ...) might make the user guide a bit too verbose in my opinion.

For this specific issue the code would look like this:
```java
Gson gson = new Gson();
String json = ...;

Type listType = new TypeToken<ArrayList<YourType>>(){}.getType();
ArrayList<YourType> list = gson.fromJson(json, listType);
```

> Also "feel free to send a PR" doesn't feel like the best contribution in my mind either.

Often, maintainers of a project cannot foresee all issues new users might run into, so I assume the intention behind inder123's comment was to find out where exactly you think the README or user guide is missing information, or in which way it could be improved.

> To satisfy my curiosity, I asked Github Copilot to just do the example, it wrote this:

The code looks correct to me, but it is probably not what most users want. Usually you have a POJO such as:
```java
class Person
    String name;
    int age;
}
```
Then you don't want to manually write the deserialization logic as shown in the generated code (which is probably also not as efficient because it first parses the JSON data into `JsonObject`) and duplicate the field names (`"name"` and `"age"`) there, but instead let Gson do all of this internally, as shown in the code block I included above.
