### ISSUE TITLE
Flatten Json Structure when keys and values have the same name

### ISSUE THREAD

**Issue by rythmic** [google/gson#1206]
Example:

```Java
class A {
 private B value = new B(5);
}

class B {
  private int value;
  public B(int v) {
    this.value = v;
  }
  
}

A a = new A();
new Gson().toJson(a); // returns {value:{value:5}}
```
Maybe there could be a GsonBuilder option to compress the json output to ```{value: 5}``` in such cases. If value would be a collection, the output would be ```{value:[{},{}...]}```

**Comment by JakeWharton** [comment]
You can use `@JsonAdapter` on the `B value` field declaration to control how it's serialized. We don't want to bake in options like this because they tend to not be generally applicable. Having an extension mechanism which allows you to control serialization, like `@JsonAdapter`, means we can prevent Gson from becoming more complex than it needs to be.
