### ISSUE TITLE
In Project RELEASE mode parse error ?  In Project DEBUG mode parse right. use version 2.8.2

### ISSUE THREAD

**Issue by golzn** [google/gson#1244]
String countryJson = AALocalFileUtil
                        .getJson(AAChooseCountryActivity.this, "country_code.json");
                List<AACountryModel> data = new Gson()
                        .fromJson(countryJson, new TypeToken<List<AACountryModel>>() {
                }.getType());

     //Get local JSON string is right.
                    Log.e("111",countryJson);

                for (AACountryModel item : data) {
            
                    Log.e("111","============");
               //but item.getZh() == null  error?????
               // down no print , then  app crash
                    Log.e("111", item.getZh());
                    Log.e("111", item.getEn());
                    Log.e("222","============");
}

**Comment by Marcono1234** [comment]
Probably not relevant anymore, but these issues which only occur in RELEASE mode are often caused by a missing or incomplete ProGuard configuration. Therefore the RELEASE build has renamed field names and Gson cannot match them with the member names in JSON anymore. See the [android-proguard-example folder](https://github.com/google/gson/tree/master/examples/android-proguard-example) for how to configure ProGuard.
