### ISSUE TITLE
Link to at least Java 7 in Javadocs

### ISSUE THREAD

**Issue by elharo** [google/gson#1258]
Various links in the API docs are 404 because they're pointing to Java 6 versions of JDK classes that Oracle has removed from the web. E.g. "close in interface AutoCloseable"  on the page http://www.javadoc.io/doc/com.google.code.gson/gson/2.8.2

**Comment by Marcono1234** [comment]
The problem is that apparently `javadoc` creates a class hierarchy that matches classes present in the JDK version of `javadoc` (and the `-source` option has not effect on this). Therefore if a `javadoc` version >= JDK 7 is used, it claims that `JsonReader` (extends `Reader`) implements `AutoCloseable` even though that interface was introduced in JDK 7 and does not exist in JDK 6.
So while linking to the JDK 7 docs would solve this for now, a similar issue could surface again for new JDK versions.

The proper solutation is probably to use the `--release 6` option (added for JDK 9), respectively `<release>6</release>` for the Maven plugin.

Note that it might be useful nonetheless to link to a newer JDK documentation, especially >= JDK 9 since that added the search feature for the Javadoc (see [JEP 225](https://openjdk.java.net/jeps/225)).

**Comment by Marcono1234** [comment]
This seems to be resolved. The latest Gson build config uses `<release>` ([source](https://github.com/google/gson/blob/gson-parent-2.11.0/pom.xml#L308)) and that seems to influence which elements are shown in the generated documentation.
For example generating the Javadoc with JDK 17 does not show `Constable` as supertype of `com.google.gson.stream.JsonToken` despite it being added as implicit supertype of enums in JDK 12.
