### ISSUE TITLE
Parse empty JSON array, the result is null when generating signed APK.

### ISSUE THREAD

**Issue by JaehoJu** [google/gson#1327]
I use Kotlin, Android.

```
val dataString = GsonBuilder().create().fromJson("""
{"friends":[],"money":null}
""", Animal::class.java)
Log.d("ABC", "log=$dataString")
```

Result from above code:
release APK - Animal(friends=null, money=null)
Run - Animal(firends=[], money=null)

Why this behavior is different. I can't find reasons or clues.

**Comment by JakeWharton** [comment]
Behavior differences between variants means that your build configuration is causing a problem. This isn't a problem with Gson itself. Since we know nothing about your build system or its configuration we are ill-suited to help. I would suggest asking your question on StackOverflow with the 'gson' tag and including more information about your build system configuration since that is where the behavioral difference is being created.
