### ISSUE TITLE
Month off by 1 when a Date is an element of a Map and toJson() is used to serialize it

### ISSUE THREAD

**Issue by ksurendra** [google/gson#1339]
new Gson().toJson(Map)

If the above Map has a Date field, the return String value contains Month off by 1. For Example, for Month of June, the return value is 5 instead of 6. While Year, Day, Hour, Min, Seconds are all correct.

And the reason this only impacts month is because month is zero-indexed in java.util.Calendar https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#MONTH “The first month of the year in the Gregorian and Julian calendars is JANUARY which is 0; the last depends on the number of months in a year.”

For example, the date saved in our cms systems is *2018-**06**-29T10:31:49.123-05:00* while the value from the above method returns as *2018-**05**-29T10:31:49.123-05:00*
 

The work around was

     customGson().toJson(Map) (instead of new Gson().toJson(Map)
     ...
     ...
     private Gson customGson() {
		GsonBuilder gsonBuilder = new GsonBuilder();
		JsonSerializer<Calendar> serializer = new JsonSerializer<Calendar>() {
			@Override
			public JsonElement serialize(Calendar src, Type typeOfSrc, JsonSerializationContext context) {
				return new JsonPrimitive(ISO8601.format(src));
			}
		};
		gsonBuilder.registerTypeAdapter(Calendar.class, serializer);
		gsonBuilder.registerTypeAdapter(GregorianCalendar.class, serializer);
		return gsonBuilder.create();
	}

**Comment by Marcono1234** [comment]
In case this is still relevant, can you please try the latest Gson version and provide a complete self-contained example? For example what exactly are you passing to `toJson` and what is this `ISO8601.format` method?

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

Pull request #2592 added a unit tests which should verify that Gson's handling of `Calendar` is correct and deserializing a value from JSON and then back to JSON produces the same output. However, note that in the JSON data produced by Gson the `month` value starts at 0 as well. So if custom user-written code is used to read this JSON data (instead of using Gson's built-in adapter), it has to consider this.
