### ISSUE TITLE
support java.sql.Date and Timestamp types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#134]
```
Apparently these two types are not supported in the DefaultTypeAdapters
(v1.3). Would be very useful if they are provided out of the box, and saves
users from writing custom serializer/deserializer.

Thanks
```

Original issue reported on code.google.com by `HSajja...@gmail.com` on 8 Jul 2009 at 5:31

**Comment by sbernard31** [comment]
Hi, 
  We use gson in [Leshan](https://www.eclipse.org/leshan/). This is an implementation of lightweight M2M protocol.
  We have a Server and a Client implementation.
  We aim compact [profile of java](http://www.oracle.com/technetwork/java/embedded/resources/tech/compact-profiles-overview-2157132.html) for the Client. Unfortunately gson has dependency to java.sql.* so we need to use the compact2 profile instead of the compact1 profiles which is ~40% bigger.
  See [leshan issue](https://github.com/eclipse/leshan/issues/58)

**Comment by davidbro-in** [comment]
@sbernard31, did you find an alternative to use compact1 profile?

**Comment by sbernard31** [comment]
No, we didn't do anything for now, but we consider using https://github.com/ralfstx/minimal-json

**Comment by henryju** [comment]
With Java 9 and modularity, it means we have to add an extra dependency on java.sql module when using Gson.

**Comment by gudenau** [comment]
Yeah, the module thing is a bit of a pain. Every time I `requires gson;` I also need to `requires java.sql;`.

Would be nice if this supported project Jigsaw in a more complete manor.

**Comment by coded9** [comment]
Hey ! Is there any hotfix for 1.4 version for sql date and time types ??
