### ISSUE TITLE
Creating json deserializer on string does not work

### ISSUE THREAD

**Issue by poldz123** [google/gson#1378]
I have json object that needs to be converted to string, but what I wanted is more of a customized string when being deserialized from the object.

Sample:
```
{
  key: [
      { value: key }
  ]
}
```

So what I really wanted is to convert one of the value within the json-array to an object's string field.

```
class Object {
  @JsonAdapter(CustomAdapter::class) val valueAndKey: String
}
```

Seems that it does not call the `deserializer` within the adapter, could it be that the default deserializer has higher percedence than the annotated ones?

I know that I can just make an object to deserialize it, but I wanted it to be deserialize to string right away since I will be using it as primary key to my database, using Room.

**Comment by NightlyNexus** [comment]
Can you make a test case? It's not clear to me how the sample JSON maps to the Object Kotlin value class.

Does Kotlin need `@field:JsonAdapter(CustomAdapter::class) val valueAndKey: String)`? Make sure the JsonAdapter annotation is added to the field.

**Comment by poldz123** [comment]
Lets say I have this adapter:

```
class KeyAndValueDeserializer: TypeAdapter<String> {
   override fun write(gsonOut: JsonWriter, value: String?) {
        gsonOut.nullValue()
    }
    override fun read(reader: JsonReader): String {
        // Just a sample, Lets do not worry of getting the actual value
        return "Expected key and value" 
    }
}
```

The data class:

```
data class Sample(
  @JsonAdapter(KeyAndValueDeserializer::class) val keyAndValue: String
)
```

Json to be deserialized:

```
{
  key: [
      { value: key }
  ]
}
```

Now when the JSON is retrieved from the API using retrofit. The adapter's read wont get called which is causing the `keyAndValue` to be null every time.

**Comment by NightlyNexus** [comment]
Looks like the model doesn't match the JSON, though, and this is unrelated to the JsonAdapter annotation.
The field name `keyAndValue` isn't a key in that JSON. The adapter isn't used, then.

**Comment by Marcono1234** [comment]
As pointed out above the field name must match the JSON member name (or you have to use `@SerializedName`). Additionally your `read(JsonReader)` function must consume the value, otherwise any subsequent `JsonReader` usage will fail. In your case you should probably call `JsonReader.skipValue()`. Though not sure how relevant that is since you mentioned your `read` implementation is just an example.

I am closing this because I assume this is no longer relevant. If you still encounter problems for this with the latest Gson version feel free to create a new GitHub issue.
