### ISSUE TITLE
Unable to deserialize data after adding fields

### ISSUE THREAD

**Issue by cirlam** [google/gson#1398]
Hi,

I have serialized a Java class within my Android app as follows:

```
static void saveSensors(Context context, List<PairedSensor> sensors) {
        if (sensors.size() > 0) {
            Gson gson = new Gson();
            String write_string = gson.toJson(sensors);
            FileOutputStream fos;
            try {
                fos = context.openFileOutput(PAIRED_SENSORS, MODE_PRIVATE);
                fos.write(write_string.getBytes());
                fos.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```

I deserialize as follows: 
```
 static List<PairedSensor> loadSensors(Context context) {
        BufferedReader input;
        File file;
        StringBuilder buffer = new StringBuilder(); //stringbuffer?
        try {
            file = new File(context.getFilesDir(), PAIRED_SENSORS); // Pass getFilesDir() and "MyFile" to read file
            FileInputStream fis = new FileInputStream(file);
            input = new BufferedReader(new InputStreamReader(fis));
            String line;
            while ((line = input.readLine()) != null) {
                buffer.append(line);
            }
            fis.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        String jsonData = buffer.toString();
        Gson gson = new Gson();
        Type listType = new TypeToken<ArrayList<PairedSensor>>() {
        }.getType();
        return gson.fromJson(jsonData, listType);
    }
```

This has been working fine up until last week, when I added a field to my base class (and upgraded from 2.8.2 to 2.8.5) - on my test devices this worked fine with accepting a new field. 

However, on my customer's devices it crashed when deserilizing with error:
`com.google.gson.p: java.lang.IllegalStateException: Expected a double but was BOOLEAN at line 1 column 1933 path $.f[0].n`
I have since rolled back to my previous version removing the new field from the class and rolling back to 2.8.2 Gson, however it still refuses to deserialize. 

Is there anything I can do to recover the data that appears to be corrupted?

**Comment by keeblebogdan** [comment]
How did you fixed this @cirlam ?

**Comment by Lantus81** [comment]
Here is how I fix this in my case
https://akristic.com/2019/03/21/how-to-fix-unable-to-deserialize-data-after-adding-fields/

**Comment by keeblebogdan** [comment]
I'm sorry but this is madness, I can't implement something like this. Thank you though!

**Comment by keeblebogdan** [comment]
Hey, guess what? It seems that obfuscation is not deterministic and JSON relies on key names being stable. I can disable obfuscation of field names for your JSON models but this is too late since users all already working with this feature and I can't simply disable obfuscation since all data will be lost.
So for the moment, guess what? I did exactly what @Lantus81 (thank you) said, but only for that class, and for all other classes, I'll add a SerializedName annotation.

**Comment by Marcono1234** [comment]
Going to close this because most likely there is nothing Gson can do to solve this. Please have a look at the [`android-proguard-example`](https://github.com/google/gson/tree/master/examples/android-proguard-example) for how ProGuard and R8 can be configured to not rename fields.

If you still have the ProGuard obfuscation mappings from your previous version, then you can as mentioned above at least add [`@SerializedName`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.9.1/com.google.gson/com/google/gson/annotations/SerializedName.html) to the affected fields based on the obfuscated field names.
