### ISSUE TITLE
fromJson() and toJson broken for Camera.Paramteres in Android 9 (android targetSdkVersion 28 and device os 9.0)

### ISSUE THREAD

**Issue by Petrakeas** [google/gson#1427]
library : "com.google.code.gson:gson:2.8.5"
gradle : 'com.android.tools.build:gradle:3.2.1'

The problem occurs when the app is built with `compileSdkVersion 28` and runs on an Android 9 device.

The [Camera.Parameters](https://developer.android.com/reference/android/hardware/Camera.Parameters)  object can't be serialized. An already seirialized instance of this object (created when the app was build with compileSdkVersion 27 and stored as a file) is deserialized into an Camera.Parameters object without the private fields set correctly. 

Perhaps the problem is related to the behavioral changes of Android 9 mentioned [here](https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces). In that case, is there a workaround?

**Comment by JakeWharton** [comment]
You need to write your own type adapter using the public API. You should
never serialize the private members of types you don't control.

**Comment by Marcono1234** [comment]
Closing this because, as mentioned above, you should not use Gson's reflection based serialization for third-party classes because it makes you dependent on their implementation details.

The workaround to this specific issue might also be to write a custom [`TypeAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapter.html) which handles the data from previous Android versions, or to write a POJO class which has the structure of that old `Camera.Parameters` data.
