### ISSUE TITLE
About the difference between toString() and getAsString() in JsonPrimitive

### ISSUE THREAD

**Issue by devonkey** [google/gson#1439]
Is the code output reasonable?
```
def main(args: Array[String]): Unit = {
    val e = new JsonPrimitive("zz")
    println(e)
    println(e.getAsString)
    println(new JsonPrimitive(e.toString))
    println(new JsonPrimitive(new JsonPrimitive(e.toString).toString))
  }
result :
"zz"
zz
"\"zz\""
"\"\\\"zz\\\"\""
```
I think the com.google.gson.streamJsonWrite.string(value:String)  is fine as a child element, but it's worth pondering when we use toString() for an independent JsonPrimitive object.

**Comment by Marcono1234** [comment]
> but it's worth pondering when we use toString() for an independent JsonPrimitive object

While the documentation has not made any guarantees for `JsonElement.toString()` and therefore also `JsonPrimitive.toString()` so far (#591), it seems many users and even Gson's own tests assume that is produces valid JSON. That means for a `JsonPrimitive` containing a String, the value must be enclosed by `"` and any nested `"` must be escaped.
So the behavior you are describing seems correct to me.

Otherwise if no enclosing `"` were used, the following would for example both produce `true` which might cause confusion: `new JsonPrimitive(true).toString()`, `new JsonPrimitive("true").toString()`
