### ISSUE TITLE
App crashes as Json element is empty String (“”) and not Object

### ISSUE THREAD

**Issue by avikr22** [google/gson#1480]
I am working on an android project and using RxAndroid, Retrofit to make API call and retrieve json. The json looks something like following :

```
{
    "result": [
        {
            "parent": "jhasj",
            "u_deviation": "skasks",
            "caused_by": "ksks",
            "u_owner_mi": {
                "link": "https://gddhdd.service-now.com/api/now/v1/table/sys_user/ghtytu",
                "value": "ghtytu"
            },
            "impact": "",  
}
]
}
```

I am using gson to parse the Json. The problem is "u_owner_mi" sometimes reruns empty string "" when there is no value assigned to it. This is making my app crash as I am expecting an object here. I get the following error : Expected BEGIN_OBJECT but was STRING

**Comment by JakeWharton** [comment]
Please ask this question on StackOverflow with the 'gson' tag so that the answer helps future travelers looking for similar solutions.

This basically requires registering a type adapter factory for all object types which wraps the built-in type adapter for that type, checks for an empty string to replace with null, or else delegates to the built-in adapter.
