### ISSUE TITLE
Deal with UTF-8 BOM

### ISSUE THREAD

**Issue by FranklinYu** [google/gson#1481]
I see that currently BOM (Byte Order Mark) for UTF-16 is dealt with properly:

https://github.com/google/gson/blob/bac26b8e429150d4cbf807e8692f207b7ce7d40d/gson/src/main/java/com/google/gson/stream/JsonReader.java#L1294-L1299

It would be awesome if BOM for UTF-8 (`EF BB BF`) is also dealt with. Currently Gson cannot decode JSON with UTF-8 BOM.

**Comment by inder123** [comment]
Send us a PR?

**Comment by JakeWharton** [comment]
Gson really shouldn't deal with BOMs because it deals with characters, not
bytes. That existing BOM handling is some unfortunate old baggage. If
you're consuming bytes you should handle the BOM yourself to determine how
to interpret those bytes as characters before passing to Gson.

Additionally, BOMs are a document-level construct whereas Gson happily
works on subsets of data where you likely will never have a BOM. For
example, OkHttp parses BOMs because a response is a full, byte-based
document which may have a BOM (ignoring the fact that it shouldn't because
of the Content-Type's charset parameter). When you ask for a character
stream or string from an OkHttp response it interprets the bytes according
to the BOM to create the characters. Responses are fundamentally a
document, but I might be using Gson to parse individual lines of a file
where BOMs don't exist.

**Comment by markkolich** [comment]
In case anyone's interested, Apache Commons IO includes a `BOMInputStream` which makes it a bit easier to consume/stream a string with a BOM:

https://commons.apache.org/proper/commons-io/javadocs/api-2.6/org/apache/commons/io/input/BOMInputStream.html

**Comment by FranklinYu** [comment]
Closing this since there is already 300+ issues. We’ll try to solve it ourselves. Thanks!
