### ISSUE TITLE
gson declares multiple JSON fields named

### ISSUE THREAD

**Issue by birdfe76** [google/gson#1493]
Hello, 
We are using 3 file jar as like **'gson-1.4.jar','gsonInternal-2.1jar','gsonStream-2.1.jar'** and it doesn't have Exception (declares multiple JSON fields named).
 
But we have to change 1 file jar( **'gson-2.3.1.jar'** ) instead of 3 file jar (as above).
and then  we are getting the below error.

 (declares multiple JSON fields named).
We've know that kind of solutions... model object **declares  annotion '@SerializedName' or  transient type.**

But our system have a lot of DTO java file. 
So I wonder that **How can we ignore that Exception**(declares multiple JSON fields named).

**Comment by diguage** [comment]
![image](https://user-images.githubusercontent.com/2121467/104421069-c8b9e680-55b5-11eb-90b6-50c97b6a9c2c.png)


I had the same problems. 

Gson versin: 2.8.6.

**Comment by Marcono1234** [comment]
Could you please provide more information why there are duplicate fields in your class hierarchy and how you would like this to be solved? E.g. should Gson prefer the field from the superclass or the subclass.

**Comment by HK-hub** [comment]
I'm also having this problem, but not in my project entity class, but in the dependency jar package I introduced - MeiliSearch.

**Comment by Marcono1234** [comment]
@HK-hub, it might be better to ask such usage questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/gson).

Also be careful when using Gson's reflection-based serialization for third party classes, because it accesses their internal fields which are most likely implementation details. So your serialization logic could break if the internal implementation of these third party classes is changed.

**Comment by minguotan** [comment]
Also has the same problem, the stackoverflow and chatgpt give no useful answers. For me, it was because the sublclass and class has the same private attribute id with. I don't know why such an obvious bug has never been fixed, looking forward a fix, thanks

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

For the latest Gson versions (>= 2.10.1) the exception explicitly mentions which fields are causing this conflict. Additionally the Troubleshooting Guide has a [section](https://github.com/google/gson/blob/main/Troubleshooting.md#duplicate-fields) about how this issue can be solved.

**Comment by dogourd** [comment]
Hi, @Marcono1234 I encountered this issue and can reproduce it in version 2.10.1. Below is a reproduction example. Does Gson have any plans to handle this scenario?
```text
Exception in thread "main" java.lang.IllegalArgumentException: Class Test$Bar declares multiple JSON fields named 'number'; conflict is caused by fields Test$Bar#number and Test$Foo#number
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:302)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.Gson.toJson(Gson.java:834)
	at com.google.gson.Gson.toJson(Gson.java:812)
	at com.google.gson.Gson.toJson(Gson.java:759)
	at com.google.gson.Gson.toJson(Gson.java:736)
	at Test.main(Test.java:16)
```
```java
public class Test {

    public static class Foo {
        protected int number;
    }

    public static class Bar extends Foo {
        protected int number;
    }

    public static void main(String[] args) {
        Gson gson = new Gson();
        Bar bar = new Bar();
        System.out.println(gson.toJson(bar));
    }
}
```

When the classes `Foo` and `Bar` are part of a third-party library, making modifications is not convenient for us. It seems that Gson is powerless in this situation.

**Comment by Marcono1234** [comment]
@dogourd, see https://github.com/google/gson/blob/main/Troubleshooting.md#duplicate-fields. Even if it is a third-party library these approaches should still be possible, just within your code:
- use a custom [`FieldNamingStrategy`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/FieldNamingStrategy.html) which renames one of the fields
- use a custom [`ExclusionStrategy`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/ExclusionStrategy.html#shouldSkipField(com.google.gson.FieldAttributes)) which skips one of the fields, assuming one of them is not actually needed\
**Important:** You must register the `ExclusionStrategy` for both serialization and deserialization, otherwise Gson will still complain.
- in the worst case write a custom [`TypeAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapter.html) for the affected class declaring the fields and manually perform serialization and deserialization of its fields

Please verify also that the third-party code you are using has really been intended for reflection-based JSON serialization (which Gson is doing). Maybe you accidentally rely on implementation details of that code which could change in incompatible ways at any time.
