### ISSUE TITLE
build 2.8.6 - increase minor?

### ISSUE THREAD

**Issue by SBD580** [google/gson#1593]
This release is compiled with newer java version what makes it incompatible with legacy code using old tools, I suggest updating the minor version as many are allowing patch updates (2.8.x etc)

**Comment by Marcono1234** [comment]
Does anyone remember what the context of this was? Only recently for Gson 2.9.0 the required Java version was increased to 7 (#2043). Though maybe back then when this issue here was created there was a faulty release?

There were however further releases after 2.8.6, so I assume there is no need for another 2.8.x release (though I am not a member of this project).

**Comment by eamonnmcmanus** [comment]
I think we can consider this obsolete. It may be that some 2.8.x release should have been 2.9.0 but we can't change the past.
