### ISSUE TITLE
Objects Serialize/Deserialize to null

### ISSUE THREAD

**Issue by LastZactionHero** [google/gson#1595]
I'm attempting to deserialize JSON with gson, but my output comes out null.

```
class Term {
  // Actual documentation uses private, didn't work for me either
  public String uuid;

  Term() {
  }

  // Tried with and without setters/getters, but doesn't seem to make a difference
  public void setUuid(String uuid){
    this.uuid = uuid;
  }
  public String getUuid() {
    return this.uuid;
  }
}

Type collectionType = new TypeToken<List<Term>>(){}.getType();
Gson gson = new Gson();
String json = "[{\"uuid\": \"aaaa\"}]";
List<Term> terms = gson.fromJson(json, collectionType);
```

Resulting list is just <[null]>. Expecting some Term objects with uuid set.

Any thoughts on what I might be doing wrong here? Even the `BagOfPrimitives` examples is serializing to a null string.

**Comment by lyubomyr-shaydariv** [comment]
Adding public constructors or accessors, or making fields public won't help unless you make your DTO class `Term` non-local:

* Gson merely does not support local classes (those that are declared in methods). This also describes why your list is output as `[null]` and not something like `[Term@01234567]`.
* In its simplest configuration `Gson` does not need your DTO classes to have any public constructors since it's able to apply some low-level object instantiation mechanics. Also, by default, Gson doesn't need any accessor methods declared (no getters no setters at all) and doesn't need the fields to be declared non-`private`. Making any of these changes wouldn't affect the object instantiation because it's merely a local class.

The following code would work for you:

```java
public final class I1595 {

	private I1595() {}

	private static final Type listOfTermsType = new TypeToken<List<Term>>(){}.getType();
	private static final Gson gson = new Gson();

	public static final class Term {
		private String uuid;
		@Override public String toString() { return uuid; }
	}

	public static void main(final String... args) {
		final List<Term> terms = gson.fromJson("[{\"uuid\": \"aaaa\"}]", listOfTermsType);
		System.out.println(terms);
	}

}
```

producing `[aaaa]` to stdout.

**Comment by KevinTyrrell** [comment]
Had the same problem as @LastZactionHero 

> @lyubomyr-shaydariv Gson merely does not support local classes

This should be warned about on the README of gson. I literally spent an hour poking through gson's implementation trying to understand why it interpreted

```java
class Cat {
    public String name;
}
String json = "{ \"name\": \"sprinkles\" }";
Cat c = g.fromJson(json, Cat.class);
```
as `null`. A very unintuitive limitation. AT LEAST throw an exception so that developers can understand why gson rejects the specified class.

**Comment by lyubomyr-shaydariv** [comment]
@KevinTyrrell
I agree to some extent, but why using anonymous and local classes that are hard to reuse outside statement blocks that declare them if such DTO classes are typically reusable by design? You might suggest/submit a PR making the current documentation at https://github.com/google/gson/blob/master/UserGuide.md#finer-points-with-objects a bit more clear (probably by providing code for "bad" and "good" scenarios):

> Fields corresponding to the outer classes in inner classes, anonymous classes, and local classes are ignored and not included in serialization or deserialization.

**Comment by lyubomyr-shaydariv** [comment]
@LastZactionHero 
no problem. The reason of why such classes are not supported is that they have implicit references to their outer classes (generated by `javac`) and those classes may be extremely hard to deserialize (if possible). I do believe it dictated the design choice. For example, if you compile the following code:

```java
class Outer {
	Outer() { // constructor, actually a statement block
		class Inner { } // local class
	}
}
```

and run `javap Outer$1Inner.class` to disassemble the inner class, it would reveal the internals:

```
Compiled from "test.java"
class Outer$1Inner {
  final Outer this$0;
  Outer$1Inner(Outer);
}
```

`Outer` can be any class that is not designed to be a data-transfer class (a test suite in your case, application-level `I1595` in my case above, etc). Package-level classes and static classes does not have any implicit references making them safe to deserialize.

**Comment by lyubomyr-shaydariv** [comment]
#1589
