### ISSUE TITLE
potential NPE issues in LinkedHashTreeMap.java

### ISSUE THREAD

**Issue by HermioneSW** [google/gson#1674]
Hi,
We are developing a new static analysis tool for catching bugs in Java code. Upon scanning your codebase we find the following:

In ```LinkedHashTreeMap.java``` (gson/src/main/java/com/google/gson/internal/LinkedHashTreeMap.java) ```rebalance``` function at line 338, we guess ```right``` can be a null since it is checked in```int rightHeight = right != null ? right.height : 0;``` at line 343, If it is indeed the case, then ```Node<K, V> rightLeft = right.left;``` and ```Node<K, V> rightRight = right.right;``` may throw a NPE at line 347 and 348.

Would you please take a look and confirm this is indeed a bug? Thanks a million!!!

**Comment by HermioneSW** [comment]
Hi, can anyone please take a look and confirm this is a bug? Thanks so much!

**Comment by Marcono1234** [comment]
If this was an NPE issue, then it would also apply to the local variable `left` because the usage pattern is the same there.

However, it looks like an NPE cannot occur because:
- `leftHeight` and `rightHight` are always >= 0 since `Node.height` is always > 0 (except if an overflow occurs)
- https://github.com/google/gson/blob/1a9469a8c5aa31deacd36b3d15347f873ce7e889/gson/src/main/java/com/google/gson/internal/LinkedHashTreeMap.java#L346
Only occurs if `rightHeight >= 2`, which is only possible if `right != null`
- https://github.com/google/gson/blob/1a9469a8c5aa31deacd36b3d15347f873ce7e889/gson/src/main/java/com/google/gson/internal/LinkedHashTreeMap.java#L364
Only occurs if `leftHeight >= 2`, which is only possible if `left != null`

**Comment by Marcono1234** [comment]
Probably obsolete because this class was removed by #1992.
