### ISSUE TITLE
Gson throws IllegalStateException when attempting to parse List or List wrapper class

### ISSUE THREAD

**Issue by J-Daniel-S** [google/gson#1676]
Good evening,

The question is linked to below.  I can repeat it here if this is inappropriate.  I also want to add that the exception does not occur if I convert to JSON String and then convert back to the class, a list of the classes, or a wrapper class for the list.  When using Files.newBufferedWriter() or Files.write() the exceptions listed on the stack overflow post.  When visually inspecting the Strings saved to file against the same String written to the console they appear identical.  I should also mention that I get the same JSON String whether using types or whether just using StocksList.class (or Stock.class). 
 I have not (as of this post) received any replies so any help Would be quite greatly appreciated.

https://stackoverflow.com/questions/60769033/gson-throws-illegalstateexception-when-attempting-to-parse-list

Thank you for your time.

**Comment by lyubomyr-shaydariv** [comment]
All the code you've provided can be greatly fixed, improved and refactored.

* No need to create multiple `Gson` instances: they are relatively expensive to instantiate, but are designed to be thread-safe and immutable therefore can be reused.
* No need to serialize to and deserialize from `java.lang.String` -- this is just expensive as long as it has to create multiple strings in the heap merely wasting the heap and time decreasing the performance.
* Why it does **not** work in your case is that `Files.readAllBytes(...)` returns `byte[]` you're trying to convert to a string. In Java, no arrays have an intuitive `toString` implementation (you can check it by simply printing any byte array to `System.out`). In order to convert it to a string (that might be a memory-consuming instance), `new String(byte[])` (or even `new String(byte[], Charset)`) is an appropriate way.
* I don't really remember how `Files` works, but there's probably no need to check the file to exist: they can be overwritten without any additional checks.
* No type tokens are necessary in this case: `StockList.class` is a `Type` too.

Essentially, all is you need is just as follows:

```java
private static final Gson gson = new GsonBuilder()
		.disableHtmlEscaping()
		.disableInnerClassSerialization()
		.create();

public static void main(final String... args)
		throws IOException {
	final StocksList before = new StocksList(ImmutableList.of(new Stock("INTC"), new Stock("HCC")));
	final Path path = Paths.get("doc.json");
	write(path, before);
	final StocksList after = read(path);
	System.out.println(after.equals(before));
}

private static void write(final Path path, final StocksList stocks)
		throws IOException {
	try ( final Writer writer = new OutputStreamWriter(new FileOutputStream(path.toFile())) ) {
		gson.toJson(stocks, writer);
	}
}

private static StocksList read(final Path path)
		throws IOException {
	try ( final Reader reader = new InputStreamReader(new FileInputStream(path.toFile())) ) {
		return gson.fromJson(reader, StocksList.class);
	}
}
```

That's it. Also, `write` and `read` methods can be improved by making them generic and accepting type information. The stock-stuff classes I've reconstructed for simplicity:

```java
final class Stock {

	final String ticker;

	Stock(final String ticker) {
		this.ticker = ticker;
	}

}
```

```java
final class StocksList {

	final List<Stock> stocks;

	StocksList(final List<Stock> stocks) {
		this.stocks = stocks;
	}

}
```

**Comment by J-Daniel-S** [comment]
Thank you very much for your answer.  Your solution resulted in a working parser class.
