### ISSUE TITLE
Does Gson 2.4 support for Java 11? If not, any timeline or recommendation?

### ISSUE THREAD

**Issue by xinmin01** [google/gson#1681]
Hi Expert,
I would appreciate if you could share your knowledge related with me? Thanks.

Regards,
Xinmin

**Comment by Marcono1234** [comment]
To my knowledge Gson supports all the latest Java versions, see also #1371.
However, there are two caveats:
- Because Gson still targets Java 7 (since Gson 2.9.0) as minimum Java version, it might not provide default adapters for all standard Java classes and might not out-of-the-box support all new language features.
- Recent Java versions [strongly encapsulate JDK internals](https://openjdk.org/jeps/403). In general it is not recommended to use Gson's reflection-based serialization for third-party classes (such as JDK classes). However, you might by accident use it without knowing it, and the strong encapsulation might break your serialization code. In that case you will have to implement custom [`TypeAdapter`s](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/TypeAdapter.html).

In general it would be best to just give it a try, and if you notice any issues check if they have already been reported and otherwise create an issues for the specific problem you are having.

**Comment by eamonnmcmanus** [comment]
FTR we're using Gson with Java 11 quite widely within Google, and experimentally with Java 17. It works fine, with the caveats noted by @Marcono1234.

**Comment by odravison** [comment]
Unfortunately using Gson 2.10 along with Java 11 to parse a object that contains `XMLGregorianCalendar `doesn't work
I'm getting this error:
`Method threw 'java.lang.reflect.InaccessibleObjectException' exception.`
even tho I registered a typeAdapter to serialize and deserialize this type of Object.

completed expection message:
`Unable to make public com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl() accessible: module java.xml does not "exports com.sun.org.apache.xerces.internal.jaxp.datatype" to unnamed module @3d5c822d`

Did I miss something?

**Comment by Marcono1234** [comment]
@odravison, could you please provide a small self contained example showing this issue?

**Comment by odravison** [comment]
Sorry to get this only right now, but I'm no long able to get that snippet.
All the best guys!

**Comment by Marcono1234** [comment]
No problem and thanks anyways for your response!

Your issue with `XMLGregorianCalendarImpl` sounds pretty similar to a Stack Overflow question, so the [answer there](https://stackoverflow.com/a/76177244) might apply as well: If you write a custom adapter for `XMLGregorianCalendar`, you have to use [`GsonBuilder.registerTypeHierarchyAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#registerTypeHierarchyAdapter(java.lang.Class,java.lang.Object)) to handle internal JDK subclasses as well.
