### ISSUE TITLE
When mapping to HashMap in Gson, the behavior of the `contains` method is sometimes strange.

### ISSUE THREAD

**Issue by pm-coffee** [google/gson#1773]
* AndroidStudio 4.0.0
* gson version: 2.8.6
* Sample Code: https://github.com/pm-coffee/GsonBugSample

* data.json : aasets json file
    ```json
    {
      "1": {
        "id": 1,
        "name": "aaa"
      },
      "2": {
        "id": 2,
        "name": "bbb"
      },
      ...
    }
    ```

* AssetsMapper.kt : loading and mapping json
    ```kotlin
    class AssetsMapper private constructor() {
    
    	companion object {
    		val instance: AssetsMapper by lazy { AssetsMapper() }
    	}
    
    	val originalMap = ConcurrentHashMap<Int, Data1>()
    	val castedMap : Map<Int, Data1>
    
    	init {
    		loadAssets()
    		castedMap = originalMap
    	}
    
    	private fun loadAssets(){
    		if(originalMap.isEmpty()) {
    			try {
    				(JsonReader(MyApp.instance.assets.open("data.json").reader(StandardCharsets.UTF_8)) as Closeable)
    					.use {
    						val rootElement = JsonParser.parseReader(it as JsonReader)
    						val listType = object : TypeToken<ConcurrentHashMap<Int, Data1>>() {}.type
    
    						originalMap.putAll(Gson().fromJson<Map<Int, Data1>>(rootElement, listType))
    					}
    			} catch (e: Exception) {
    				Log.e("loadAssets()", "error", e)
    			}
    		}
    	}
    
    }
    ```

originalMap.contains is false. Is this a bug?
```kotlin
val originalMapDataContains = AssetsMapper.instance.originalMap.contains(2)// <----- result is false. this result is strange.
val castedMapDataContains = AssetsMapper.instance.castedMap.contains(2)// <----- result is true
```

**Comment by lyubomyr-shaydariv** [comment]
The `contains` methods from the `originalMap` object is **directly** bound to [a legacy method](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#contains-java.lang.Object-) from the JDK.

> `public boolean contains(Object value)`
>
> Legacy method testing if some key maps into the specified value in this table. This method is identical in functionality to containsValue(Object), and exists solely to ensure full compatibility with class Hashtable, which supported this method prior to introduction of the Java Collections framework.

However, the `castedObject` instance type is unknown at the compile time, and Kotlin uses its inline overload

> `@kotlin.internal.InlineOnly`
> `public inline operator fun <@kotlin.internal.OnlyInputTypes K, V> Map<out K, V>.contains(key: K) : Boolean = containsKey(key)`

that is bound to the [method](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#containsKey-java.lang.Object-) you're expecting for.

Not a Gson bug but an _unexpected_ clash between a legacy method from JDK and an operator from Kotlin.

Interesting enough, the infix syntax, `2 in originalMap` produces a warning in my default Kotlin settings (in IntelliJ IDEA though): _Method contains from ConcurrentHashMap may have unexpected semantics: It calls containsValue instead of containsKey_.
But it's funny, that the "Replace overloaded operator with function call" ignores that warning and replaces the infix operator with the clashing `contains` method invocation, not `containsKey`.

**Comment by pm-coffee** [comment]
So that's what happened.
Sorry to hear that it's not a gson bug.

But thank you. I understand.

**Comment by lyubomyr-shaydariv** [comment]
@pm-coffee could you please close the issue? Thank you.

**Comment by TWiStErRob** [comment]
FYI this is tracked and partially fixed in Kotlin:
Hashtable https://youtrack.jetbrains.com/issue/KT-48007
ConcurrentHashMap https://youtrack.jetbrains.com/issue/KT-18053
