### ISSUE TITLE
[Question] : is gson still maintained?

### ISSUE THREAD

**Issue by radityagumay** [google/gson#1821]
Rationale behind this is, gson looks like not actively maintained. The [last PR](https://github.com/google/gson/commit/ceae88bd6667f4263bbe02e6b3710b8a683906a2) was on may. and looks like there's no roadmap on gson to provide [new features and fix bugs.](https://github.com/google/gson/pulls)

Will appreciated if the maintainer able to put some thoughts on this. 

Thank you!

**Comment by Marcono1234** [comment]
I am not a maintainer / member of this project and had the same question the last months as well and always thought about creating an issue too because activity here has sadly slowed down.

There are several critical issues (with corresponding pull requests) which have not been touched for a rather long time (subjective selection):
- Issues with generic parameter being used multiple times: #1391
- ProGuard issues with enums: #1495
- `ISO8601UtilsTest` being faulty (#1665, #1687, #1781)
- Optional `java.sql` module dependency: #1707
- Problem with SecurityManager: #1712

It appears @joel-leitch, one of the original maintainers, is not very active on GitHub anymore. @swankjesse and @JakeWharton are not active here either. I am not completely familiar with their biography, but if I understand it correctly they (or one of them) quit their job at Google and are now working at Square where they are working on https://github.com/square/moshi, a competitor of Gson. Maybe they do not even have the GitHub project roles and permissions anymore to directly work on Gson.
@inder123 is the one who made the most recent changes, but it looks like they are not that active at the moment either.

It is not my goal to blame them for the lack of activity, they put great efforts in this project in the past and are the reason for the popularity of it. It is completely understandable that after more than 10 years, the motivation of working on the same project decreases. Especially when (as it is likely the case for all projects) design flaws or decisions hindering future development become apparent over time. And as with all open source projects, enough free time might also not always be available.

However, because Gson is still widely used it is important that a clear decision is made about how Gsons future development (if any) will look like. Otherwise users will be forced to switch to other frameworks when bugs remain unfixed. While switching to other frameworks is not necessarily bad, being forced to do this creates extra stress and work for the users; it should ideally happen voluntarily.
Would it at least be possible to keep developing Gson in _maintenance mode_: Only bug fixes are implemented, but no major new features are added?

**Comment by xileftenurb** [comment]
I found this anwser on reddit written by @swankjesse

https://www.reddit.com/r/androiddev/comments/684flw/why_use_moshi_over_gson/dgx3gpm?utm_source=share&utm_medium=web2x&context=3

In short, it seem Gson is already in maintenance mode because it was mostly replaced by "moshi", a new project build by some of the same contributor with less short-comming than Gson

**Comment by mleonhard** [comment]
Moshi is a suitable alternative to Gson.  I just switched my code over.

https://github.com/square/moshi

Moshi throws exceptions in cases where Gson silently returns `null`.  I'm happy with this.

Moshi doesn't support `Optional` yet ([square/moshi#1329](https://github.com/square/moshi/issues/1329)).

**Comment by Marcono1234** [comment]
Thanks @eamonnmcmanus and @cgdecker for bringing some activity back into this project! What are the future plans for Gson?

**Comment by anandr781** [comment]
Is Gson actively maintained

**Comment by cgdecker** [comment]
We've taken ownership of this project so that we can do basic maintenance and such (for example the release we made last month) but we don't have any specific plans for it at the moment.

**Comment by kliakos** [comment]
> We've taken ownership of this project so that we can do basic maintenance and such (for example the release we made last month) but we don't have any specific plans for it at the moment.

Please fix Java 16 related issues.

**Comment by eamonnmcmanus** [comment]
I am planning to spend some time this month studying open issues and PRs, consistent with the maintenance mode that @cgdecker mentioned. We are unlikely to add new features at this point but we can attempt to address some important issues. The list compiled by @Marcono1234 above will likely be very helpful in this regard.

I think we've addressed the question asked in this issue, so I'm going to close it.
