### ISSUE TITLE
JsonDeserializer throws runtime error when parameterized type is not of type collection and JsonElement is of type JsonArray

### ISSUE THREAD

**Issue by bitforce** [google/gson#1857]
When `jsonElement` is of type `JsonArray` and the `JsonDeserialization<T>` type is not a collection, Gson will always throw an `IllegalStateException`.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/24510536/106795661-58d4d400-6628-11eb-9db4-c81fe068df8e.png">

Above is the full code, note that `Example` is an empty class.
Below is an image of the direct deserialization in debug mode. Note that the contents of `instrumentJson` are irrelevant and that it is a correctly streamed `JsonObject` from a `JsonArray`.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/24510536/106793902-0c889480-6626-11eb-949c-f290b7f700af.png">

However, if I decide to serialize to most-any other Objects, the `jsonDeserializerContext#deserialize` has no problem whatsoever. 

<img width="602" alt="deserialize object" src="https://user-images.githubusercontent.com/24510536/106794060-45c10480-6626-11eb-8c25-044e4be472ea.png">

<img width="601" alt="random" src="https://user-images.githubusercontent.com/24510536/106794662-27a7d400-6627-11eb-8447-b91d2c16a2b5.png">

<img width="601" alt="stream support" src="https://user-images.githubusercontent.com/24510536/106794664-28406a80-6627-11eb-9a2b-a19cdf5942be.png">

So my educated guess is if the current type is not matching the `JsonElement` subtype (`JsonObject` or `JsonArray`), then it causes problems.

Below is confirmation that `jsonElement` is of type `JsonArray`

<img width="602" alt="image" src="https://user-images.githubusercontent.com/24510536/106794198-7a34c080-6626-11eb-99ba-4d01c0a6a7da.png">

My problem is *sovled* if I change the return type to `List<Example>` as seen below.

<img width="1258" alt="problem solved" src="https://user-images.githubusercontent.com/24510536/106794870-6473cb00-6627-11eb-8575-b8bd021496cc.png">

But this does not fix my use-case of only wanting to return the first element from this list. It doesn't fit my design pattern either. 

## Context
The original issue is the designers of the API I am deserializing from, thought it would be _cool_ for a singular resource endpoint to instead of return a `JsonObject`, return a `JsonArray` that would always be of size 1. It is confirmed that this array will always be size one but they have no plans to change the API and I would prefer to keep the `list#get(0)` logic out of my controller if possible and return the single element from the deserializing class. 

## Major Inquiry
It is possible to deserialize a `JsonArray` without *having* to return a collection type when implementing `JsonDeserializer<T>`?

**Comment by Marcono1234** [comment]
Could you please provide a self-contained small code example demonstrating this issue?
And could you also please include the full stack trace of the exception? I am unable to find any code in this project which throws an exception with the message "This is not a JSON Array" (not even the prefix "This is not"); are you sure that Gson is actually throwing that exception? It looks more like Gson is only wrapping it inside a `JsonSyntaxException`.

**Comment by bitforce** [comment]
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at <my package dir>.ExampleDeserializer.lambda$deserialize$0(ExampleDeserializer.java:25)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at <my package dir>.ExampleDeserializer.deserialize(ExampleDeserializer.java:26)
	at <my package dir>.ExampleDeserializer.deserialize(ExampleDeserializer.java:16)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at <my package dir>.ExampleDeserializationTest.main(ExampleDeserializationTest.java:17)

```

**Comment by bitforce** [comment]
Below is a way to run this code and recreate the issue:

```
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

public class ExampleDeserializationTest  {

  public static void main(String[] args) {
    Gson gson = new GsonBuilder().registerTypeAdapter(Example.class, new ExampleDeserializer())
         .create();
    JsonArray array = new JsonArray();
    JsonObject object = new JsonObject();
    object.addProperty("name", "bitforce");
    array.add(object);
    Example example = gson.fromJson(array, Example.class);
    System.out.println(example);
  }

}
// main
```

```
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;

import java.lang.reflect.Type;
import java.util.stream.StreamSupport;

public class ExampleDeserializer implements JsonDeserializer<Example> {
  @Override
  public Example deserialize(
      JsonElement jsonElement, Type type, JsonDeserializationContext jsonDeserializationContext)
      throws JsonParseException {
    return StreamSupport.stream(jsonElement.getAsJsonArray().spliterator(), false)
        .map(
            instrumentJson ->
                (Example) jsonDeserializationContext.deserialize(instrumentJson, Example.class))
        .findFirst()
        .orElseThrow(RuntimeException::new);
  }
}
// deserializer
```

```
public class Example {}
```

**Comment by Marcono1234** [comment]
Thanks! The exception message does indeed come from Gson, but it appears you are using Gson 2.8.1 (or older). It might be worth upgrading to the latest version (2.8.6).

The problem is that the `JsonDeserializer` you are registering is calling itself: Initially you are telling Gson to deserialize your Example JSON array as `Example.class` which works fine but then your JsonDeserializer calls `jsonDeserializationContext.deserialize(instrumentJson, Example.class)` which invokes itself again (since it is registered for `Example.class`), this time with a single Example JSON object which therefore causes the exception you are seeing.

If you already know that your data is an array of Example and you only want the first one, then it might be easiest to directly access the `JsonArray` element or to use a `JsonReader` (depending on the form in which you receive the JSON data):
```java
public static void main(String[] args) throws IOException {
    JsonArray array = new JsonArray();
    JsonObject object = new JsonObject();
    object.addProperty("name", "bitforce");
    array.add(object);
    
    System.out.println(fromJsonArray(array));
    
    try (Reader jsonString = new StringReader("[{\"name\":\"bitforce\"}]")) {
        System.out.println(fromJsonString(jsonString));
    }
}

private static Example fromJsonArray(JsonArray jsonArray) {
    if (jsonArray.size() > 0) {
        return new Gson().fromJson(jsonArray.get(0), Example.class);
    } else {
        throw new IllegalArgumentException("...");
    }
}

private static Example fromJsonString(Reader jsonString) throws IOException {
    JsonReader jsonReader = new JsonReader(jsonString);
    jsonReader.beginArray();
    if (jsonReader.hasNext()) {
        return new Gson().fromJson(jsonReader, Example.class);
    }
    throw new IllegalArgumentException("...");
}
```

Otherwise if the Example array appears nested within other model classes, it becomes slightly more complicated. How this can be solved depends on the actual model classes you are using.
You could implement a custom [`TypeAdapterFactory`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/TypeAdapterFactory.html) which creates an adapter which begins reading the array and then calls a delegate for deserializing the `Example` object. If you always wan't JSON arrays of Example to be deserialized as single Example, then you could register that factory on the `GsonBuilder`. Otherwise you could use the [`@JsonAdapter`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/annotations/JsonAdapter.html) annotation on fields of type `Example` and then specify the  `TypeAdapterFactory` for that annotation (though don't use `Gson.getDelegateAdapter(...)` in the `TypeAdapterFactory` then because it is currently broken for `@JsonAdapter`, see #1028).

**Comment by bitforce** [comment]
Thank you for the deep insight; apologies, I did not include the version I was using (`2.8.0`). Consider this closed.
