### ISSUE TITLE
Type information not included in serialization meaning Object is not deserialized correctly

### ISSUE THREAD

**Issue by carlospalmaroldan** [google/gson#1883]
Backstory: Using jackson library there's a feature called polymorphic type validation that allows the user to include class information in the json by means of these lines of code:

```
PolymorphicTypeValidator ptv = LaissezFaireSubTypeValidator.instance;
objectMapper.activateDefaultTyping(ptv, ObjectMapper.DefaultTyping.NON_FINAL);
```

What this does is that it adds the type information to the json generated by the library so that when deserializing we automatically get the proper class. 

```
["java.util.HashMap", {
	"person1": ["com.Feature", {
		"time": 1618934834317,
		"lifespan": -1,
		"value": ["com.FeatureTest$Person", {
			"address": ["com.FeatureTest$Address", {
				"houseNumber": "1"
			}]
		}]
	}]
}]
```

The problem with Jackson is that it requires non-arg constructors for all objects and that's why we couldn't keep on using it. 

Now I am looking for a way to emulate that behavior using GSON.  The idea is to be able to  deserialize something like this:

```
public class Feature{
   private String name;
   private int score;
   Object value;
}
```

The value property should be transformed to the correct class.

**Comment by Marcono1234** [comment]
> The problem with Jackson is that it requires non-arg constructors for all objects and that's why we couldn't keep on using it.

Note that Gson uses JDK's `sun.misc.Unsafe` class to create instances of classes without no-arg constructor. Therefore you have to make sure it is present for the JRE you are using. For example Android does not have that class (as far as I know), and when using tools for the Java Platform Module System such as `jlink` you might need to make sure to include the `jdk.unsupported` module.

In general please keep in mind that you should only deserialize trusted JSON when retrieving the class names from the JSON data. Otherwise this could in the worst case lead to remote code execution when an attacker is able to deserialize any class.

You could probably use a [`TypeAdapterFactory`](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/com/google/gson/TypeAdapterFactory.html) which creates an adapter which then first reads the class name, then retrieves the respective adapter from the `Gson` object passed to `TypeAdapterFactory.create(...)` and then uses that adapter to deserialize the object.
Depending on where you would want this behavior, you could then either register the factory on the `GsonBuilder` or use the [`@JsonAdapter`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/annotations/JsonAdapter.html) annotation. In your `Feature` example above you could for example annotate the `value` field with `@JsonAdapter`.

Maybe the code of the Gson Extras class [`RuntimeTypeAdapterFactory`](https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java) is also a helpful reference.

Though are you sure Jackson really does not support your usecase? I am not very familiar with it, but from what I have read there might be multiple ways of supporting classes without no-arg constructor.

**Comment by Marcono1234** [comment]
Closing this because I think it has been answered. Please let us know if you have further questions.
