### ISSUE TITLE
new Gson().toJsonTree slow

### ISSUE THREAD

**Issue by quantrpeter** [google/gson#1893]
Hi
    Is it possible to run "new Gson().toJsonTree(hashMap);" faster? I need to serialize a hashmap object 100,000 times for my RISC-V simulator.
Thanks
Peter

**Comment by Karlatemp** [comment]
You should cache the `Gson` object, not allocate it every time

```java
class Holder {
    static final Gson gson = new Gson();
}
```
Then use `Holder.gson` instead of `new Gson()`

**Comment by quantrpeter** [comment]
@Karlatemp not much different

**Comment by Marcono1234** [comment]
Could you please provide more information about how you are using the serialized JSON?
For example in case you are writing it to the file system or only need the String representation, using the different `Gson` methods would be more appropriate since they avoid having to create the complete JSON data as in-memory `JsonElement`s.

Similarly if it is not one HashMap you need to serialize multiple times but instead 100,000 separate ones which (in some way) form the complete JSON document, then it might be faster to write them all at once, e.g. by serializing the parent container (if any) of them, or using a single `JsonWriter` for the `Gson` method calls to write all of them to the same JSON file / String.

**Comment by Marcono1234** [comment]
Closing because no further information was provided. In case you still think the performance is not good enough, please try to provide a short, complete example showing the performance issues, or include the output of performance analysis tools.
