### ISSUE TITLE
the toJson method return empty when serializing anonymous inner Map 

### ISSUE THREAD

**Issue by yongxing510** [google/gson#2023]
# Gson version
2.8.9

# Java / Android version

OSX jdk 1.8.0_231

# Description

the toJson method return empty when serializing anonymous inner Map 

```java
public static void main(String[] args) throws Exception {
        Map<String, Object> inputMap = new HashMap<>() {{
            put("1", new HashMap() {{
                put("2", "inner");
            }});
        }};

        String result = new Gson().toJson(inputMap);
        // the result is {}
    }
```

## Expected behavior
the expected result is {"1": {"2":"inner"}}

in addition, the result is null  under jdk11.0.6 (built-in idea 2021.2)

**Comment by Marcono1234** [comment]
This is probably the 'expected' behavior. Gson does not serialize and deserialize anonymous classes (see #298) because it can be difficult to properly handle captured and enclosing instances.
See [existing issues here about "double brace initialization"](https://github.com/google/gson/issues?q=is%3Aissue+double+brace).

Since you are using Java > 8 I would recommend using the collection factory methods such as [`Map.of`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#of(K,V)) to create the maps. Using anonymous classes to create collections has its disadvantages, see [this StackOverflow answer](https://stackoverflow.com/a/27521360).

----

Note that I am not a member of the Gson project.

**Comment by yongxing510** [comment]
thanks very much
