### ISSUE TITLE
Not a JSON Object: For a valid number array

### ISSUE THREAD

**Issue by manikantayarramsetti1** [google/gson#2028]
# Gson version
2.8.9

# Java / Android version
openjdk version 17  2021-09-14

# Description
I am trying to get Json tree as given below 
```
JsonParser.parseReader(new StringReader("[0.796862903256]"))
                .getAsJsonObject();
```

## Expected behavior
I except a valid json array

## Actual behavior
java.lang.IllegalStateException: Not a JSON Object: [0.796862903256]

**Comment by Marcono1234** [comment]
It sounds like you are confusing the JSON data types. Gson has the following type hierarchy:
- `JsonElement`
  - `JsonArray`
  - `JsonNull`
  - `JsonObject`
  - `JsonPrimitive`

`JsonObject` represents the JSON 'object' data type, as [defined by the RFC](https://datatracker.ietf.org/doc/html/rfc8259#section-4), that is `{ ... }`.
However, as you mention, your data is a JSON array, therefore you have to use [`getAsJsonArray()`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/JsonElement.html#getAsJsonArray()) instead of `getAsJsonObject()`.
