### ISSUE TITLE
Is there a way to parse kotlin's value class?

### ISSUE THREAD

**Issue by sungbeenkim** [google/gson#2236]
i want parse to value class of kotlin.

If anyone has a way please let me know 🥲🥲🥲

**Comment by Marcono1234** [comment]
Is there a specific problem you have, for example an exception being thrown?

Note that Gson is mainly written with focus on Java. It might support some or most usages with Kotlin, but probably not all. A JSON library with explicit Kotlin support might be better suited, for example:
- https://github.com/square/moshi
- https://github.com/FasterXML/jackson-module-kotlin
- https://github.com/Kotlin/kotlinx.serialization
- ...

**Comment by Marcono1234** [comment]
I am going to close this because no answer has been provided. If you still experience this with the latest Gson version, feel free to comment here again with more details.

However, as mentioned above Gson does not fully support Kotlin and there are multiple existing GitHub issues here about this already.
