### ISSUE TITLE
Serializing not as expected when instancing within double braces

### ISSUE THREAD

**Issue by boring-plans** [google/gson#2242]
# Gson version

2.10

# Java / Android version

Java

# Used tools

- [x] Maven; version: 3.8.1
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

When creating an instance of a nested class in a normal way:

```java
class Test {
    public String name;
    public Test2 test2;

    public void setName(String name){
        this.name = name;
    }

    public void setTest2(Test2 test2){
        this.test2 = test2;
    }
}
class Test2{
    public String info;
    public void setInfo(String info){
        this.info = info;
    }
}

public class Main {
    public static void main(String[] args) {
        Gson gson = new Gson();
        
        Test test = new Test(){{setName("foo");}};
        test.setTest2(new Test2(){{setInfo("bar");}});
        String result = gson.toJson(test);
    }
}
```
The result is:

```json
{"name":"foo","test2":{"info":"bar"}}
```

But when instancing `Test2` also in a double braces way:

```java
public class Main {
    public static void main(String[] args) {
        Gson gson = new Gson();
        
        Test test = new Test(){{ setName("foo"); setTest2(new Test2(){{ setInfo("bar"); }}); }};
        String result = gson.toJson(test);
    }
}
```

`test2` part is gone:

```json
{"name":"foo"}
```

## Expected behavior

Nested part will also be serialized when in a double braces way.

## Actual behavior

It will not.

**Comment by Marcono1234** [comment]
Double brace initialization actually creates an anonymous class, and Gson does not allow anonymous classes at the moment. Unfortunately it does not handle them in a very user friendly way and just serializes a JSON `null`, which is omitted from your output because `new Gson()` omits `null` values, see also [`GsonBuilder.serializeNulls()`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#serializeNulls()).

There is an open discussion about this in #1510, therefore I am closing your issue. Unfortunately no backward compatible solution for this has been found yet.

**Comment by eamonnmcmanus** [comment]
Just to add that double-brace initialization is usually best avoided anyway, as detailed [here](https://blog.jooq.org/dont-be-clever-the-double-curly-braces-anti-pattern/).

**Comment by boring-plans** [comment]
@eamonnmcmanus @Marcono1234 
Learned a lot! Thanks~👻
