### ISSUE TITLE
convert String to List, spotbugs plugin found a SE_BAD_FIELD bug,how to fix

### ISSUE THREAD

**Issue by lyc25** [google/gson#2425]
# Gson version

2.8.6

# Java / Android version

1.8

# Used tools

- [ ] Maven; version: 3.6.3

# Description

convert String to List,it  is working,but spotbugs plugin found a SE_BAD_FIELD bug,how to fix it:
[ERROR] Class xxx.ServiceTreeClientImpl$6$1 defines non-transient non-serializable instance field this$1 [xxx.ServiceTreeClientImpl$6$1] In ServiceTreeClientImpl.java SE_BAD_FIELD

` public List<String> getResult(String s) {
              ArrayList<String> result;
              result =
                  GsonUtils.gson().fromJson(s, new TypeToken<ArrayList<String>>() {}.getType());
              return result;
            }`

## Expected behavior

no bugs

## Actual behavior

spotbugs plugin found a SE_BAD_FIELD bug:
[ERROR] Class xxx.ServiceTreeClientImpl$6$1 defines non-transient non-serializable instance field this$1 [xxx.ServiceTreeClientImpl$6$1] In ServiceTreeClientImpl.java SE_BAD_FIELD

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```

```

**Comment by Marcono1234** [comment]
The SpotBugs bug pattern [`SE_BAD_FIELD`](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#se-bad-field) seems to be related to Java Serialization, and does not appear to be related to Gson at all. See for example [this Stack Overflow question](https://stackoverflow.com/q/4861228) for potential solutions to this.

Note however that Gson does not require that your classes implement `Serializable`, so if you don't actually use Java Serialization[^1], then the easiest solution would be to remove `implements Serializable` from your classes.

[^1]: In general you should avoid Java Serialization because it is unsafe, see for example the [Secure Coding Guidelines for Java SE](https://www.oracle.com/java/technologies/javase/seccodeguide.html#8).

**Comment by lyc25** [comment]
> The SpotBugs bug pattern [`SE_BAD_FIELD`](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#se-bad-field) seems to be related to Java Serialization, and does not appear to be related to Gson at all. See for example [this Stack Overflow question](https://stackoverflow.com/q/4861228) for potential solutions to this.
> 
> Note however that Gson does not require that your classes implement `Serializable`, so if you don't actually use Java Serialization[1](#user-content-fn-1-978a56520e2efb6b5be155a7ef335379), then the easiest solution would be to remove `implements Serializable` from your classes.
> 
> ## Footnotes
> 1. In general you should avoid Java Serialization because it is unsafe, see for example the [Secure Coding Guidelines for Java SE](https://www.oracle.com/java/technologies/javase/seccodeguide.html#8). [leftwards_arrow_with_hook](#user-content-fnref-1-978a56520e2efb6b5be155a7ef335379)

Thank You for Your reply

**Comment by Marcono1234** [comment]
No problem; I am going to close this issue then because as mentioned above, it seems to be unrelated to Gson.
