### ISSUE TITLE
'Abstract classes can't be instantiated!' error, even after applying R8 rules mentioned in Troubleshooting.md

### ISSUE THREAD

**Issue by StupidRepo** [google/gson#2748]
# Gson version
`2.11.0`

# Java / Android version
Android 14

# Used tools

- [x] Gradle; version: 8.7
- [x] ProGuard; version: Unsure.

# Description
I followed [the steps in Troubleshooting.md][steps] to fix the R8 abstract classes error, however it didn't work. Eventually, I tried the following:
```
-dontshrink
-dontobfuscate
-dontoptimize
```
...with R8 still enabled, and it worked fine. Then, I commented out each `-dontX` line until I was left with:
```
-dontshrink
#-dontobfuscate
#-dontoptimize
```
...and this seemed to work perfectly! I could obfuscate and optimise, and I would no longer encounter this annoying error!

So it seems telling ProGuard not to shrink anything allows for this error to disappear.
## Expected behavior
I expected to be able to use shrinking, obfuscating, and optimising without any problems.

## Actual behavior
Instead, the `Abstract classes can't be instantiated!` error appeared.

[steps]: https://github.com/google/gson/blob/main/Troubleshooting.md#-jsonioexception-abstract-classes-cant-be-instantiated-r8

**Comment by Marcono1234** [comment]
If you are using Gson 2.11.0 with R8, then it should have used the [default configuration](https://github.com/google/gson/blob/gson-parent-2.11.0/gson/src/main/resources/META-INF/proguard/gson.pro) automatically.

Did you try `<init>(...);` (instead of just `<init>()`) as well? Currently only no-args constructors are kept, but if your class only has constructors with arguments, then they might not have been kept[^1].
One way to test this would be to disable R8, and then use `GsonBuilder#disableJdkUnsafe()`; that might then throw an exception mentioning that your class has no no-args constructor.

Could you please also share the code of the affected class (and whether it is a nested / local class)?

[^1]: Note that non-`static` inner classes have the enclosing instance as implicit constructor parameter.

**Comment by StupidRepo** [comment]
Hey @Marcono1234, yes I did try `<init>(...);` too.
Here is one of my classes that are affected by this:
```kt
@Entity
data class Announcement(
    @PrimaryKey val id: Int,
    val title: String,
    val description: String,
    val author_name: String,
    val timestamp: String,

    @TypeConverters(AttachmentsConverter::class) val attachments: List<Attachment>
)
```

**Comment by Marcono1234** [comment]
Ok, your class does not have a no-args constructor, but also you are not using `@SerializedName` (or did you omit them here)? So the default `gson.pro` rules won't be effective.
Also, if you enable obfuscation but don't use `@SerializedName`, this will likely lead to [issues the next time you update your app](https://github.com/google/gson/blob/main/Troubleshooting.md#android-app-broken-after-app-update).

I think `<init>(...);` should work here then:
```
-keepclassmembers class com.example.Announcement {
  <init>(...);
}
```

But maybe it is easiest here to just annotate your class with Android's `@Keep` (not sure if that has other undesired side effects)? Otherwise the `.pro` file could become outdated if you rename classes or packages (not sure if Android tooling detects that).

----

As side note: Since you are not using a no-args constructor and are using Kotlin, maybe it would be better to switch to a library with proper Kotlin support (see the warning on Gson's README) and which calls the args constructor (instead of using `Unsafe` as done by Gson).
Using Gson might work fine, but as soon as you start using Kotlin parameter default values or assume that nullness is respected, it will break.

**Comment by StupidRepo** [comment]
I did not omit `@SerializedName`, I decided not to use it however I might want to now after seeing this. I did see that warning on the README, and too decided to ignore that. Unfortunately, I did try default values once and, like you said, it broke and didn't work :(

Maybe I will switch libraries, maybe I won't. I'm not really sure. Thanks for this though! I'll consider everything you have said and decide whether to stick with Gson or switch to something else.

And with that, this issue is now closed. Thanks again for the help! 👍🏽

**Comment by Marcono1234** [comment]
But note that if that other JSON library uses reflection like Gson (and not code generation), then you will probably have to use something similar to Gson's `@SerializedName` there as well to prevent property names from being renamed. That library probably also has instructions for ProGuard / R8 users.
