### ISSUE TITLE
The int type is converted to a floating point type

### ISSUE THREAD

**Issue by small-thanks** [google/gson#2780]
# Gson version
2.11.0

# Java / Android version
JDK 1.8 

# Used tools
    implementation("com.google.code.gson:gson:2.11.0")

- [ ] Maven; version: 
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description
![Image](https://github.com/user-attachments/assets/5d64efbd-136c-4c0c-b36f-c702d414ac2c)

The int type is converted to a floating point type

## Expected behavior 
{"age":123} ->{age=123}

## Actual behavior
{"age":123} ->{age=123.0}

# Reproduction steps
        String json = "{\"age\":123}";
        System.out.println("gson" + new Gson().fromJson(json, Map.class));
        System.out.println("gson" + new Gson().fromJson(json, new TypeToken<Map<String, Object>>() {
        }.getType()));
        System.out.println("gson" + new Gson().fromJson(json, new TypeToken<Map<String, String>>() {
        }.getType()));
        System.out.println(json);

1. ...
2. ...

# Exception stack trace

```

```

**Comment by Marcono1234** [comment]
When you tell Gson to deserialize as `Object` and it encounters a JSON number, it will by default deserialize it as `Double` regardless of the format of the number.

You can solve this by either specifying the exact number type, e.g. `Integer` instead of `Object`, or by using a different [`ToNumberPolicy`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/ToNumberPolicy.html) or implementing your own [`ToNumberStrategy`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/ToNumberStrategy.html) and specifying it with [`GsonBuilder#setObjectToNumberStrategy`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#setObjectToNumberStrategy(com.google.gson.ToNumberStrategy)). See https://github.com/google/gson/issues/2210#issuecomment-1263913714 for more details.
