### ISSUE TITLE
Support immutable objects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#287]
```
GSON should use Unsafe to instantiate objects without invoking the default 
constructor. That would permit GSON to support immutable objects, similarly to 
how Java serialization does it.
```

Original issue reported on code.google.com by `jessewil...@google.com` on 7 Feb 2011 at 11:01

**Comment by marcosalis** [comment]
Any updates on this one? Jackson has been supporting @JsonCreator for constructors for ages, and it's also the only (clean) way to instantiate an object for deserialization without using reflection, especially in case of immutable objects.
I would expect this to be a very common use case scenario (J. Block, Effective Java item 15, "Minimize Mutability"), but maybe I'm missing something?

**Comment by inder123** [comment]
@marcosalis  InstanceCreator let's you plug in custom instances.

Can you share an example of how JsonCreator is used to return an immutable object?

**Comment by marcosalis** [comment]
@inder123 as far as I know, `InstanceCreator` is only used for the object's instance creation, rather than setting the actual deserialized values to the object fields. This is only useful when you can't have a parameterless constructor in the model class. Field setting is still done via reflection (again, correct me if I'm wrong).

With Jackson you achieve it simply by doing this (just the first example I found):
```java
public class Point {
  private final int x, y;

  @JsonCreator
  public Point(@JsonProperty("x") int x, @JsonProperty("y") int y) {
   this.x = x;
   this.y = y;
  }
 }
```

**Comment by inder123** [comment]
You can do the same with a TypeAdapter or a JsonDeserializer.

With JsonDeserializer you can use context.deserialize() to map a complex JsonObject to a field.

**Comment by marcosalis** [comment]
@inder123 sure thing, however using these two methods bear the significant disadvantage of having to completely override the standard deserialization process, and having to process every single field manually: this can be quite verbose (and time consuming) in case of complex models.

I still think that having the same kind of annotation processing would be extremely useful for developers. Should I create a separate improvement ticket or is it something that Gson is not planning on implementing anytime soon?

**Comment by inder123** [comment]
A pull request with a proposal on how to do this will be great. However, please note that we set a high bar for adding anything to the API, so don't be disheartened if we eventually reject that PR. Thanks.

**Comment by lachlanm** [comment]
Hi @marcosalis

Stumbled across this issue and saw your comment regarding annotation processors. If you're interested I have a solution to your problem within my gson 'extension'  library. 

Here is a link to the project:
https://github.com/lachlanm/gsonpath/

With regards to your wish for proper immutability support, I have recently added a feature which generates code based on interfaces. These interfaces are used to generate an immutable pojo and a proper type adapter which will use the constructor correctly. 

It would certainly be nice to have something like this in the base gson project, but if you're interested, you can use this library in conjunction with gson. 

Here is a link to the details of how it works:
https://github.com/lachlanm/gsonpath/blob/master/guides/interfaces.md

**Comment by marcosalis** [comment]
Hey @LachlanMcKee, apologies for the late reply. Thank you, I'll check your library out, it seems very interesting! I'd be curious to know, have you done any performance tests to compare deserialization speeds between the standard Gson pattern and your library?

**Comment by LachlanMcKee** [comment]
Hi @marcosalis 

I have done a degree of performance tests (I will need to publish these sometime...). The main performance benefit is obtained from the initial deserialization. This is because Gson normally generates a type adapter when it is first required, and it is then cached. This is why they always recommend hanging on to your gson instance.

It very much depends on how complicated your JSON is as well. If it is a heavily complex structure that normally requires multiple type adapters, and you generate a simple type adapter with my library, there will be a very noticeable performance boost on the first deserialization.
