### ISSUE TITLE
Fix interpretation of trailing comma when setLenient() is true.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#494]
```
The following code exhibits the issue:

    StringReader reader = new StringReader("{foo: ['bar', 'baz',]}");
    JsonReader jsonReader = new JsonReader(reader);
    jsonReader.setLenient(true);
    JsonParser parser = new JsonParser();
    JsonElement root = parser.parse(jsonReader);
    assertEquals(
        "Trailing comma should be ignored like in ECMAScript 5.",
        2,
        root.getAsJsonObject().get("foo").getAsJsonArray().size());

Currently, GSON returns an array that corresponds to:

    ["bar", "baz", null]

Instead of:

    ["bar", "baz"]

This is atrocious. The current behavior is consistent with bad browser behavior 
from the last decade. The expected behavior is consistent with ECMAScript 5, as 
well as any programmer who has ever wanted trailing commas to be ignored so 
that it is easier to write lists of things. Here is more information on the 
badness of the current JSON spec:

    http://bolinfest.com/essays/json.html

Please, please fix this. Anyone who uses JSON for a config language wants to be 
able to write data like this:

   [
     "foo",
     "bar",
   ]

such that it is possible to add something to the list without having to clean 
up the comma from the previous line. The current behavior is incredibly 
counterintuitive.

Also, while we're on the subject, the trailing comma should also be supported 
for map entries:

  {
    "foo": 42,
    "bar": 24,
  }

Again, this makes it considerably easier to maintain JSON data files.

```

Original issue reported on code.google.com by `bolinf...@gmail.com` on 6 Jan 2013 at 11:58

**Comment by BoD** [comment]
I've just been bitten by this.
Just to clarify: I am not using `jsonReader.setLenient(true);` but don't get an exception while parsing files with trailing commas - is it expected behavior?

**Comment by BoD** [comment]
Wow I've just seen bug #401 and from what I understand, `jsonReader.setLenient(true);` is simply ignored, and therefore (please correct me if I'm wrong),
1/ trailing commas are always valid
2/ they are interpreted as null items
3/ there's no way to change this

🙀

**Comment by swankjesse** [comment]
🙀

**Comment by chris-henderson-alation** [comment]
Just accidentally stumbled across this while writing tests for our Hadoop REST bindings. It was incredibly surprising and we were lucky to accidentally trigger the bug.

Please do correct this, it's not what anybody expects.

**Comment by BoD** [comment]
You mean more hideous than the current "happily parse invalid JSON without a warning and result in a very surprising results that nobody should reasonably expect" behavior?

**Comment by JakeWharton** [comment]
You can use `getAdapter().fromJson()` to work around our bad default of using lenient parsing.

**Comment by mitasov-ra** [comment]
Stumbled across this bug just now and really surprised that that issue is closed.

As @BoD said this behaviour, or I really should say **this bug**, is not a joke, it's a serious thing, causing unexpected hard to catch bugs. And yes, it reproduces even if `lenient` is `false`

I really hope this bug will be revisited, analysed and fixed without somewhat insulting "Write better JSON" answers.

**Comment by eamonnmcmanus** [comment]
I do think there's a good case to be made for a proper "strict mode" in Gson, which would accept _only_ fully-conformant JSON input. As noted in the documentation for [`JsonReader.setLenient`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonReader.html#setLenient(boolean)), there are some things that Gson currently allows even when `lenient` is `false`. (Trailing commas should probably be added to that list.)

We couldn't make strict mode be the default, because that would risk breaking existing users, but we could certainly recommend its use.

I logged #2295 to track having a strict-mode feature.

**Comment by Marcono1234** [comment]
> there are some things that Gson currently allows even when `lenient` is `false`. (Trailing commas should probably be added to that list.)

@eamonnmcmanus, are you sure about that? For me a non-lenient `JsonReader` rejects a trailing comma with a `MalformedJsonException`. See also the relevant code:
https://github.com/google/gson/blob/3adf2ad7488cbc1e297540410d218edf97c6bc76/gson/src/main/java/com/google/gson/stream/JsonReader.java#L567-L569

@mitasov-ra, please follow the advise of the "Lenient JSON handling" section of the [`Gson` class documentation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/Gson.html) to get non-lenient behavior, except for derivations from the JSON specification listed by `JsonReader.setLenient`, which were mentioned above.

**Comment by eamonnmcmanus** [comment]
> For me a non-lenient `JsonReader` rejects a trailing comma with a `MalformedJsonException`.

So is the [earlier comment](https://github.com/google/gson/issues/494#issuecomment-1365848138) simply wrong? We probably still should have a strict mode for the other reasons detailed in #2295, but if trailing commas are already disallowed when not using lenient mode I think that is perfectly fine. I personally am skeptical whether anybody should ever use lenient mode at all, since it recognizes a more or less random superset of correct JSON.
