### ISSUE TITLE
deserialize arbitrary collections of objects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#510]
```
Add a config option to Gson so that it can optionally serialize an object's 
class along with its other fields (simply a String com_google_gson_java_class = 
"com.package.SomeClass"). Then when deserializing an arbitary collection of 
objects they could be deserialized correctly.

This seems like a quick/easy fix to overcome a pretty big limitation.
```

Original issue reported on code.google.com by `rhd...@gmail.com` on 26 Apr 2013 at 4:46

**Comment by Marcono1234** [comment]
Including the Java class name in JSON and loading that class during deserialization reduces portability of the JSON data to other programming languages, and can have a big security impact because malicious users would be able to load and deserialize arbitrary classes (which might not have been designed for deserialization).

Maybe the actual problem described here is #231, or might be solved by the [`RuntimeTypeAdapterFactory`](https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java).

I am closing this issue because this was created 9 years ago and no other user reacted on this feature request.
