### ISSUE TITLE
Add 'end' method to JsonWriter 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#522]
```
"Writes the end of the current context. If the current context is an array 
context, this method writes the end-of-array character (']'). If the current 
context is an object context, this method writes the end-of-object character 
('}'). After writing the end of the current context, the parent context becomes 
the new current context."

Description from JSON processing JSR 
https://json-processing-spec.java.net/nonav/releases/1.0/pfd-draft/javadocs/java
x/json/stream/JsonGenerator.html#writeEnd()
```

Original issue reported on code.google.com by `denis.st...@gmail.com` on 14 Jun 2013 at 10:16

**Comment by Marcono1234** [comment]
Closing this issue because it is 9 years old and it is not completely clear to me how useful this method would be. To properly write to a `JsonWriter` you have to know whether you are currently writing an array or object because writing an object requires additional `name(String)` calls. Therefore you also know whether you have to use `endArray()` or `endObject()` at the end.

If you do need such an `writeEnd()` method, please explain your use case.
