### ISSUE TITLE
Support new Guava collections by default

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#526]
```
What steps will reproduce the problem?
1. Create Guava collection as a member element of a class. Example:

import java.util.Collection;
import java.util.Map;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class GsonExample {
    private final Multimap<String, String> map = HashMultimap.create();
    private final Map<String, Collection<String>> asMap;
    public GsonExample() {
        map.put("a", "a");
        map.put("a", "b");
        map.put("b", "b");
        asMap = map.asMap();
    }
    public static void main(String[] args) {
        GsonExample ex = new GsonExample();
        Gson g = new GsonBuilder().setPrettyPrinting().create();
        System.out.println(g.toJson(ex));
    }
}

What is the expected output? What do you see instead?
Expected:
{
  "map": {
    "b": [
      "b"
    ],
    "a": [
      "b",
      "a"
    ]
  },
  "asMap": {
    "b": [
      "b"
    ],
    "a": [
      "b",
      "a"
    ]
  }
}

Actual:
{
  "map": {},
  "asMap": {
    "b": [
      "b"
    ],
    "a": [
      "b",
      "a"
    ]
  }
}

What version of the product are you using? On what operating system?
I am using Gson 2.2.4 and Guava 14.0.1 on Windows 7 x64, Java 7u25.

Please provide any additional information below.
This is a feature enhancement, not a bug. Thanks!
```

Original issue reported on code.google.com by `martin.j...@gmail.com` on 24 Jun 2013 at 3:33

**Comment by dimo414** [comment]
I appreciate why Gson doesn't want to depend on Guava, but it's very surprising and error-prone that these objects serialize to an empty collection. Are there any options that could make the status quo better without directly adding that dependency?

For instance, could the collection types be special-cased in Gson and detected by reflection? Or could any better hints be included in Guava (without it in turn depending on Gson)?

There doesn't appear to be any such type adapters added to https://github.com/google-gson/typeadapters yet either. Does it make sense to leave this issue open until that's addressed, at least?

**Comment by inder123** [comment]
@dimo414 Not sure if Guava is used widely enough (for example on Android) to warrant special casing. It has gotten too bloated, and JDK 8 and 9 are providing good alternates.

But it does make sense to provide type adapters for Guava. Consider starting the effort by contributing partial support. Thanks.

**Comment by dimo414** [comment]
To my knowledge JDK 8 and 9 don't introduce anything like Guava's collection types (`Multiset`, `Multimap`, `Table`, `BiMap`), and these types are fairly widely used (at least outside Android). A reflection-based solution would avoid any sort of bloat issues, as well.

Nevertheless, If you don't want to support them natively that's understandable. Is there any way to improve Guava to be more Gson-friendly? I can try to make that happen if it's possible.

If the only viable solution is to create a separate type adapter, could it at least be included in this project, rather than relegated to the google-gson/typeadapters project? That seems very hard to discover (e.g. not mentioned anywhere in the User Guide), and there appear to be other special type adapters in this project (e.g. [`proto`](https://github.com/google/gson/blob/master/proto/src/main/java/com/google/gson/protobuf/ProtoTypeAdapter.java)). [Guava](https://mvnrepository.com/artifact/com.google.guava) has much more usages than [protobuf](https://mvnrepository.com/artifact/com.google.protobuf) in Maven.

**Comment by inder123** [comment]
Do these classes extends List, Map? I think we support all subclasses of those natively.

**Comment by dimo414** [comment]
No, that's the issue, these are ["new" collection types](https://github.com/google/guava/wiki/NewCollectionTypesExplained). They've been around since Guava was first released.

**Comment by inder123** [comment]
I see. If Guava was willing to have a dependency on Gson, then it can use a JsonAdapter annotation on each of these collections and customize the behavior.

Until then, it is best to just create sample type adapters.
