### ISSUE TITLE
Special characters encoding is not working 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#567]
```
What steps will reproduce the problem?
1. Have a string with special characters (it may be any thing like symbol too)
2. try to convert that into a class object using fromJson
3. the special characters were not getting mapped to the corresponding varaible

What is the expected output? What do you see instead?
   The expectation is all the special characters to be mapped correctly. but it is not mapped correctly

What version of the product are you using? On what operating system?
  gson 2.2.4, Windows 7

Please provide any additional information below.

```

Original issue reported on code.google.com by `smileven...@gmail.com` on 19 Mar 2014 at 4:29

**Comment by ParitoshVaidya** [comment]
I am having same issue. `GSON` is not parsing unicode. Please post solution if anybody found it.

**Comment by HunterPillu** [comment]
I'm having same issue . gson showing special characters .  Here is my string content
[response.txt](https://github.com/google/gson/files/2089947/response.txt)

**Comment by inder123** [comment]
If you want us to address this issue, please provide a PR with a test-case that fails.

**Comment by Marcono1234** [comment]
As mentioned above, please test this with the latest Gson version and provide a small example demonstrating the issue.

Note that Gson by default escapes HTML characters. This can be disabled with `GsonBuilder.disableHtmlEscaping()`. However, for any compliant JSON parsing (including Gson) it does not matter whether HTML characters are escaped in the JSON output or not, the represented data is still the same.

**Comment by adedhelaajay** [comment]
Here is one example:
```
        String focusField = "{\"outputOnlyInfo\":\"=0\"}";
        Gson gson = new Gson();
        String convertedString = gson.toJson(JsonParser.parseString(focusField).getAsJsonObject());
        System.out.println(convertedString);
```        
Outputs unicode like this:
`{"outputOnlyInfo":"\u003d0"}`

However using `Gson gson = new GsonBuilder().**disableHtmlEscaping**().create();`
we get:
{"outputOnlyInfo":"=0"}
although not a html tag, this is the expected result. "=0"

**Comment by Marcono1234** [comment]
@adedhelaajay, it seems you are right that `=` probably does not have to be escaped for "HTML safety". However Gson has escaped it already for a [long time](https://github.com/google/gson/blob/57d1f32de5bf3a7dd54613384cc7e979fba2660b/gson/src/main/java/com/google/gson/Escaper.java#L58). And this behavior is mentioned in the [`JsonWriter.setHtmlSafe` documentation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonWriter.html#setHtmlSafe(boolean)).

I assume it could be considered whether `=` really should be escaped, but for your example both `"=0"` and `"\u003d0"` represent the same data and any compliant JSON parser should consider the represented data to be equal. The `"\u003d0"` variant is just more verbose.

**Comment by eamonnmcmanus** [comment]
The concrete code example from @adedhelaajay is very helpful!

I think the concern here is that Gson doesn't round-trip strings in the expected way. It's unfortunate that HTML escaping is the default, but given that it is, you would also see the same non-round-trip behaviour for characters that really would need to be escaped in HTML, like `&` and `<`. If we change the example string to have `"<0"` instead of `"=0"` then the resultant JSON has `"\u003c0"`, which would indeed be required if you were (for some reason) including this in HTML text. So if you want to be able to round-trip strings through JSON, you need to turn off HTML escaping.

I don't think there's anything we can do here except possibly improve the documentation. Changing the defaults would potentially break existing users.
