### ISSUE TITLE
MsgPack && BSON support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#590]
```
It's possible to serialize to MsgPack or BSON providing custom 
com.google.gson.stream.JsonWriter implementation. 

Unfortunally MsgPack and BSON operates yet another "primitive" type - binary 
(byte array). MsgPack and BSON provide effective way to store binary data. JSON 
use BASE64 string for this. Unfortunately JsonWriter doesn't know about this - 
there are no "value(byte[] value)" method.

I propose to add such method (com.google.gson.stream.JsonWriter can do base64 
convertion themself) so custom JsonWriter implementation can distinguish 
between "plain string" and "binary data";


```

Original issue reported on code.google.com by `dimzon...@gmail.com` on 21 Aug 2014 at 12:52

**Comment by flavius-mester** [comment]
Up for this. Has anybody looked into this?

**Comment by bozaro** [comment]
+1

**Comment by vmichalak** [comment]
+1

**Comment by Marcono1234** [comment]
Is the intention here to write a `byte[]` as Base64 encoded JSON string value (e.g. `{"data": "dGVzdA=="}`) or are you proposing that the Base64 encoded data is directly written without any quotes?

In case of the former, you can write a `TypeAdapter<byte[]>` performing the Base64 encoding, as shown for example [here](https://gist.github.com/elucash/ee4d294cb0d920fc227d993aebf6d53c) (probably have to ask the author for permission). Note that there are some more popular implementions based on `JsonSerializer` (such as [this](https://gist.github.com/orip/3635246)), but they are probably not as efficient as the `TypeAdapter` one. You can then either register the adapter for all `byte[]` instances with [`GsonBuilder.registerTypeAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#registerTypeAdapter(java.lang.reflect.Type,java.lang.Object)), or apply it only for specific fields with [`@JsonAdapter`](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/annotations/JsonAdapter.html).

Note that this might not be very efficient for large binary arrays, but unfortunately Gson does not support writing JSON string values using a writer yet (#1367).

I am not sure if adding a dedicated `JsonWriter` method which performs this Base64 encoding would be a good idea. `byte[]` does not map directly to any of the JSON types, so API-wise it would probably make more sense to use a `TypeAdapter` (or `JsonSerializer`) for conversion.

**Comment by eamonnmcmanus** [comment]
I agree with @Marcono1234. We already have the means for users to encode `byte[]` as Base64, but they have to define that explicitly with a `TypeAdapter<byte[]>`. It's not clear that Base64 encoding is what everybody would want for `value(byte[])`. Also, unlike the existing `value(T)` methods, `byte[]` does not correspond to a standard JSON type.

**Comment by burnpanck** [comment]
Actually, I believe the real request here was to enable alternate output formats beside JSON, namely MsgPack and BSON - both of which are very similar. In general, one can do this already today by writing a custom implementation of `JsonWriter` - except that these two formats offer one additional "value type" (byte arrays), which JSON doesn't. So in order to enable building a full-featured MsgPack or BSON serialiser based on Gson (through a custom `JsonWriter`), `JsonWriter` would require a `value(byte[] value)` method. This in turn raises the question how the real JSON serialiser should handle that, and the suggestion was to use Base64 encoding universally. I don't think that the latter is a good idea, but why not simply let the JsonWriter throw and exception unconditionally, if ever a `byte[]` value propagates all the way to the JSON writer? Users can still register a `TypeAdapter`.
