### ISSUE TITLE
Patch for /trunk/gson/src/main/java/com/google/gson/JsonDeserializer.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#626]
```
Remove incorrect parentheses
```

Original issue reported on code.google.com by `mfisc...@yext.com` on 3 Feb 2015 at 1:06

Attachments:
- [JsonDeserializer.java.patch](https://storage.googleapis.com/google-code-attachments/google-gson/issue-626/comment-0/JsonDeserializer.java.patch)

**Comment by Marcono1234** [comment]
Seems to apply still, see #661 for the needed changes. Though there are futher issues with that code sample, see #1425.

**Comment by Marcono1234** [comment]
It is not completely clear what this issue was about since the attachment does not exist anymore, but based on the linked pull request it was most likely about the erroneous `()` in the code sample of the `JsonDeserializer` documentation. That problem was fixed by #2192, therefore I will close this issue.
