### ISSUE TITLE
Passing JSONObject [from org.json] (not JsonObject [from com.google.gson]) to gson.toJson()

### ISSUE THREAD

**Issue by divyenduz** [google/gson#673]
Something like this 
```        
fileString = "{\"name\":\"divyendu\", \"age\": \"23\"}";
JSONObject jsonObject = new JSONObject(fileString); 
Gson gson = new Gson();
System.out.println(jsonObject.toString());
System.out.println(gson.toJson(jsonObject));
System.out.println(jsonObject.toString().equals(gson.toJson(jsonObject)));
```
The output of 1st S.O.P is {"age":"23","name":"divyendu"}
The output of 2nd S.O.P is {"map":{"age":"23","name":"divyendu"}} (it gets wrapped in a 'map' key)
The output of 3rd S.O.P is false
How can I avoid it being wrapped in S.O.P, without using StringBuilder which is called when I call `jsonObject.toString()` directly. It was causing a OutOfMemory error for me.

**Comment by JakeWharton** [comment]
You can write a `TypeAdapter<JSONObject>` which walks the tree structure of the `org.json` model objects and emits the tree into Gson's `JsonWriter`. Similarly, if you need to parse JSON into the `org.json` model from Gson (which is a really strange thing to do). You would do the same but with `JsonReader`.

You could also write a `JsonSerializer<JSONObject>` (and, again, if you wanted a `JsonDeserializer<JSONObject>`) to deal with Gson's DOM model instead of streaming model which, funny enough, is very similar to `org.json`'s API.

The scope of doing this is outside what I'm willing to write, and not something that's a bug or feature request on Gson. If you are unable to figure this out, I suggest you post on StackOverflow about how to write a `TypeAdapter` for `org.json.JSONObject` as that community is primed to help and serves as a much better place for storing the solution for future searchers.

**Comment by divyenduz** [comment]
Thanks

**Comment by lingyfh** [comment]
[org.json.JSONObject and org.json.JSONArray JsonSerializer and JsonDeserializer](https://github.com/google/gson/issues/782#issuecomment-419424521)
