### ISSUE TITLE
JsonReader not strict about JSON document consumption

### ISSUE THREAD

**Issue by NightlyNexus** [google/gson#835]
Say I have a class:
```final class MyType {}```

and a `TypeAdapter`:
```
final class MyTypeAdapter extends TypeAdapter<MyType> {
  // ...
  @Override public MyType read(JsonReader in) throws IOException {
    in.beginObject();
    return new MyType();
    }
}
```
Note the missing `in.endObject()` call.

My calling code:
```
String json = "{}";
Gson gson = new GsonBuilder().registerTypeAdapter(MyType.class, new MyTypeAdapter()).create();
StringReader stringReader = new StringReader(json);
MyType myType = gson.fromJson(stringReader, MyType.class);
```
The above will correctly fail (`JsonIOException: JSON document was not fully consumed.`).

However, using a `JsonReader` instead (`gson.fromJson(new JsonReader(stringReader), MyType.class)`) will not fail.
Is this working as intended?

**Comment by JakeWharton** [comment]
If you are passing a `JsonReader` instance then it's your responsibility to do the assertion.

The implementation of `fromJson(String, Class<?>)` is:
```java
JsonReader jsonReader = newJsonReader(json);
Object object = fromJson(jsonReader, classOfT);
assertFullConsumption(object, jsonReader);
return object;
```

In the case where you are the one creating the `JsonReader` there's no opportunity to assert completion since you may just be deserializing part of the whole document.

**Comment by NightlyNexus** [comment]
Oh, yes, I should have dug one step deeper into that. Thanks. Makes sense.
