### ISSUE TITLE
json-sanitizer

### ISSUE THREAD

**Issue by andrespontt** [google/gson#841]
Hi,
This is not a bug, is a question. Sorry if this is not the right place to put it.

I was requested to include the OWASP json sanitizer to gson.fromJson function, anybody knows if GSON sanitize the string out of the box or this is something that I should include manually?

https://www.owasp.org/index.php/OWASP_JSON_Sanitizer

Thanks in advance.

**Comment by eliezerjg** [comment]
dont sanitize from what i know, i believe the only available option is using https://mvnrepository.com/artifact/com.mikesamuel/json-sanitizer/1.2.3

**Comment by Marcono1234** [comment]
When creating JSON data, Gson supports HTML escaping; enabled by default for the `Gson` class (see also [`GsonBuilder#disableHtmlEscaping()`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html#disableHtmlEscaping())), disabled by default for the `JsonWriter` class (see [`JsonWriter#setHtmlSafe(boolean)`](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/stream/JsonWriter.html#setHtmlSafe(boolean))).

Since version 2.11.0 Gson also supports a [`Strictness` API](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/Strictness.html) to make Gson strictly adhere to the JSON specification (by default it is lenient).

Whether that helps and suffices for you probably depends on your use case. OWASP json-sanitizer provides more functionality than that.
