### ISSUE TITLE
Help~Please tell me how to change.Thanks

### ISSUE THREAD

**Issue by LunYing** [google/gson#891]
public static <T> PackageModel<T> getData(Class<T> cls) {
        String json = "{\"code\":0,\"data\":{\"account\":\"test009\",\"createdBy\":\"\",\"email\":\"123@qq.com\",\"enabledFlag\":1,\"id\":\"8735\",\"language\":\"zh\",\"name\":\"test123\",\"phone\":\"18566219120\",\"timeZones\":\"77\",\"type\":\"8\"},\"ok\":true}";
        Gson gson = new Gson();
        PackageModel<T> vPackageModel = gson.fromJson(json, new TypeToken<PackageModel<T>>() {
        }.getType());
        return vPackageModel;
    }

erro:java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.jimi.app.entitys.UserInfo

**Comment by JakeWharton** [comment]
Generics are erased so that `T` becomes `Object` and therefore Gson creates a `Map` instead of whatever `T` was supposed to be. You need to wrap `cls` in the `PackageModel` parameterized type and there's no good API to do that.

Can you ask your question on StackOverflow since it's a usage problem not a bug with the library? Use the 'gson' tag, and also feel free to link it here.
