### ISSUE TITLE
 java.lang.CloneNotSupportedException: Class doesn't implement Cloneable

### ISSUE THREAD

**Issue by lytasky** [google/gson#951]
Caused by: java.lang.CloneNotSupportedException: Class doesn't implement Cloneable
java.lang.Object.clone (Object.java:155)
com.google.gson.internal.$Gson$Types$ParameterizedTypeImpl.<init> ($Gson$Types.java:451)
com.google.gson.internal.$Gson$Types.canonicalize ($Gson$Types.java:101)
com.google.gson.reflect.TypeToken.getSuperclassTypeParameter (TypeToken.java:87)
com.google.gson.reflect.TypeToken.<init> (TypeToken.java:62)

does this has a solution？

**Comment by Marcono1234** [comment]
The only versions of `ParameterizedTypeImpl` where line 451 has a `clone()` call seems to be:
- https://github.com/google/gson/blob/b2a9d872dba1fb3bde57421b7b953f666cb59df4/gson/src/main/java/com/google/gson/internal/%24Gson%24Types.java#L451
- https://github.com/google/gson/blob/14ba59fa8858126dbe0c3e645a84c7de3bf2361a/gson/src/main/java/com/google/gson/internal/%24Gson%24Types.java#L451

However, in both cases the object on which `clone()` is called is an array. So this should not throw a `CloneNotSupportedException` (also because cloning an array is shallow).

But since this GitHub issue is quite old and seems to be the only one about this problem, it might not be relevant anymore.

**Comment by eamonnmcmanus** [comment]
Closing as stale. Feel free to log a new issue if the problem exists with the latest Gson.
