### ISSUE TITLE
JsonPrimitive number strange behavior using float and double

### ISSUE THREAD

**Issue by rascio** [google/gson#972]
I found that having:

        JsonPrimitive prim = new JsonPrimitive(0.1d);
        JsonPrimitive prim2 = new JsonPrimitive(0.1f);

        System.out.println("prim.equals(prim2) = " + prim.equals(prim2));

It print the `equals` as **false**, isn't this a bug? Why having this distinction when it doesn't exists in simple json?

**Comment by iProdigy** [comment]
You are experiencing this behavior because:

1. The number 0.1 results in a repeating decimal in binary, which causes 0.1f != 0.1d as floats and doubles have varying degrees of error in representing 0.1

2. [The implementation of JsonPrimitive#equals for numbers](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/JsonPrimitive.java#L324) checks direct equality (==). When java doesn't find 0.1f to be equal to 0.1d, JsonPrimitive won't either.

For JsonPrimitive to not have this behavior, the equals test would have to use an epsilon value to determine absolute error, but this can be inherently problematic.

**Comment by Marcono1234** [comment]
As described above it sounds like this behavior is correct, so I will close this issue.
