### ISSUE TITLE
Convert Simple Object which extends java.util.Date return {}

### ISSUE THREAD

**Issue by isCoding** [google/gson#993]
I have a simple class named C1:
```
class A extends Date{

    private String aaa;

    public String getAaa() {
        return aaa;
    }

    public void setAaa(String aaa) {
        this.aaa = aaa;
    }
}
```
Then,using default Gson convert it to json.
```
public static void main(String[] args) {
        C1 a = new C1();
        Gson gson = new Gson();
        String s = gson.toJson(a);

        System.out.println(s);  //output --> {}

        Date aa = new Date();

        System.out.println(gson.toJson(aa)); //output-->"Jan 10, 2017 2:54:02 PM"
    }
```

The output is different to `gson.toJson(new Date())`  

Anything need I do?

**Comment by andrespontt** [comment]
it will be different since Gson is using a different AdapterType writer to convert it to Json.

You can either create a custon JsonSerializer or you can populate the aaa variable in the constructor with super.toString(), the output will be different though.

**Comment by Marcono1234** [comment]
If you want your `C1` instance to also be serialized as `Date` then you have to explicitly tell Gson to do this: `gson.toJson(a, Date.class)`

Otherwise it uses the runtime type of the object and because you have not registered a custom type adapter for your class Gson will use reflection. The field `aaa` seems to be omitted because its value is null (see also `GsonBuilder.serializeNulls()`) and `java.util.Date` fields all seem to be `transient` and are therefore ignored (though you should not relying on reflection-based serialization of internal JDK fields in the first place).
